import type { Movie, Episode } from './types/movie';
export type { Movie, Episode };
import { loadCsvCatalog } from './csvCatalog';

export const movieData: Movie[] = [
  {
    id: 1,
    title: "Echoes of Tomorrow",
    year: 2025,
    genre: "Sci-Fi",
    rating: 8.9,
    narrator: "Rocky Kimomo",
    duration: "2h 15m",
    quality: "1080p FHD",
    fileSize: "1.45 GB",
    description: "In a cyber-kinetic Kigali 2077, an elite memory investigator discovers a temporal breach altering future events. Authentic Kinyarwanda narration by Rocky Kimomo.",
    image: "/fallback-poster.png",
    backdrop: "/fallback-poster.png",
    trending: true,
    telegramChannelPost: "https://t.me/fiestaflix_movies/101",
    telegramBotLink: "https://t.me/FiestaFlixBot?start=movie_1",
    directStreamUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4"
  },
  {
    id: 2,
    title: "Midnight Shadows",
    year: 2024,
    genre: "Thriller",
    rating: 8.5,
    narrator: "Junior Giti",
    duration: "1h 52m",
    quality: "1080p FHD",
    fileSize: "1.18 GB",
    description: "A detective with insomnia uncovers an underground syndicate operating beneath the glowing city neon. Tense commentary by Junior Giti.",
    image: "/fallback-poster.png",
    backdrop: "/fallback-poster.png",
    trending: true,
    telegramChannelPost: "https://t.me/fiestaflix_movies/102",
    telegramBotLink: "https://t.me/FiestaFlixBot?start=movie_2",
    directStreamUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4"
  },
  {
    id: 3,
    title: "Ocean's Heart",
    year: 2025,
    genre: "Adventure",
    rating: 9.1,
    narrator: "Savimbi",
    duration: "2h 30m",
    quality: "4K UHD",
    fileSize: "2.10 GB",
    description: "An oceanographer and a rogue deep-sea diver venture into uncharted Mariana trenches where lost civilizations slumber.",
    image: "/fallback-poster.png",
    backdrop: "/fallback-poster.png",
    trending: true,
    telegramChannelPost: "https://t.me/fiestaflix_movies/103",
    telegramBotLink: "https://t.me/FiestaFlixBot?start=movie_3",
    directStreamUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4"
  },
  {
    id: 4,
    title: "Love in Paris",
    year: 2024,
    genre: "Romance",
    rating: 7.8,
    narrator: "Dylan",
    duration: "1h 44m",
    quality: "1080p FHD",
    fileSize: "980 MB",
    description: "Two estranged musicians cross paths along the Seine during an autumn downpour. Emotional storytelling narrated by Dylan.",
    image: "/fallback-poster.png",
    backdrop: "/fallback-poster.png",
    trending: false,
    telegramChannelPost: "https://t.me/fiestaflix_movies/104",
    telegramBotLink: "https://t.me/FiestaFlixBot?start=movie_4"
  },
  {
    id: 5,
    title: "Neon Nights",
    year: 2025,
    genre: "Action",
    rating: 8.7,
    narrator: "Rocky Kimomo",
    duration: "2h 05m",
    quality: "1080p FHD",
    fileSize: "1.62 GB",
    description: "High-octane street racing meets corporate espionage on the wet highways of Tokyo. Electrifying energy by Rocky Kimomo.",
    image: "/fallback-poster.png",
    backdrop: "/fallback-poster.png",
    trending: true,
    telegramChannelPost: "https://t.me/fiestaflix_movies/105",
    telegramBotLink: "https://t.me/FiestaFlixBot?start=movie_5"
  },
  {
    id: 6,
    title: "Forest of Secrets",
    year: 2024,
    genre: "Fantasy",
    rating: 8.3,
    narrator: "Yanga",
    duration: "2h 10m",
    quality: "720p HD",
    fileSize: "890 MB",
    description: "Ancient spirits awaken when an industrial expedition invades the primordial Nyungwe canopy. Legend narrated by Yanga.",
    image: "/fallback-poster.png",
    backdrop: "/fallback-poster.png",
    trending: false,
    telegramChannelPost: "https://t.me/fiestaflix_movies/106",
    telegramBotLink: "https://t.me/FiestaFlixBot?start=movie_6"
  },
  {
    id: 7,
    title: "Space Odyssey",
    year: 2025,
    genre: "Sci-Fi",
    rating: 9.0,
    narrator: "PK",
    duration: "2h 45m",
    quality: "4K UHD",
    fileSize: "2.85 GB",
    description: "An interstellar vessel journeys across a wormhole in search of a habitable sanctuary for humanity. Narration with epic flair by PK.",
    image: "/fallback-poster.png",
    backdrop: "/fallback-poster.png",
    trending: true,
    telegramChannelPost: "https://t.me/fiestaflix_movies/107",
    telegramBotLink: "https://t.me/FiestaFlixBot?start=movie_7"
  },
  {
    id: 8,
    title: "The Last Laugh",
    year: 2024,
    genre: "Comedy",
    rating: 7.5,
    narrator: "Junior Giti",
    duration: "1h 38m",
    quality: "1080p FHD",
    fileSize: "920 MB",
    description: "Three bumbling con artists accidentally steal a diplomat's priceless pet parrot. Hilarious punchlines and jokes by Junior Giti.",
    image: "/fallback-poster.png",
    backdrop: "/fallback-poster.png",
    trending: false,
    telegramChannelPost: "https://t.me/fiestaflix_movies/108",
    telegramBotLink: "https://t.me/FiestaFlixBot?start=movie_8"
  },
  {
    id: 9,
    title: "Mountain Peak",
    year: 2025,
    genre: "Drama",
    rating: 8.6,
    narrator: "Gaheza",
    duration: "2h 02m",
    quality: "1080p FHD",
    fileSize: "1.30 GB",
    description: "A mountaineer confronts past grief while scaling the treacherous northern face of Mount Karisimbi during a blizzard.",
    image: "/fallback-poster.png",
    backdrop: "/fallback-poster.png",
    trending: false,
    telegramChannelPost: "https://t.me/fiestaflix_movies/109",
    telegramBotLink: "https://t.me/FiestaFlixBot?start=movie_9"
  },
  {
    id: 10,
    title: "Ghost Protocol",
    year: 2024,
    genre: "Horror",
    rating: 8.2,
    narrator: "Savimbi",
    duration: "1h 48m",
    quality: "1080p FHD",
    fileSize: "1.10 GB",
    description: "An abandoned broadcast tower begins transmitting chilling signals from spirits trapped in the analog frequencies.",
    image: "/fallback-poster.png",
    backdrop: "/fallback-poster.png",
    trending: false,
    telegramChannelPost: "https://t.me/fiestaflix_movies/110",
    telegramBotLink: "https://t.me/FiestaFlixBot?start=movie_10"
  },
  {
    id: 11,
    title: "Cyber Warrior",
    year: 2025,
    genre: "Action",
    rating: 8.8,
    narrator: "Sankara",
    duration: "2h 12m",
    quality: "4K UHD",
    fileSize: "2.40 GB",
    description: "An augmented operative goes rogue to dismantle a biometric control grid threatening free citizens. Masterclass narration by Sankara.",
    image: "/fallback-poster.png",
    backdrop: "/fallback-poster.png",
    trending: true,
    telegramChannelPost: "https://t.me/fiestaflix_movies/111",
    telegramBotLink: "https://t.me/FiestaFlixBot?start=movie_11"
  },
  {
    id: 12,
    title: "Ancient Mysteries",
    year: 2024,
    genre: "Documentary",
    rating: 8.0,
    narrator: "Sankara",
    duration: "1h 35m",
    quality: "1080p FHD",
    fileSize: "850 MB",
    description: "Archeological discoveries reveal the forgotten kings and metallurgical masters of the ancient Great Lakes empires.",
    image: "/fallback-poster.png",
    backdrop: "/fallback-poster.png",
    trending: false,
    telegramChannelPost: "https://t.me/fiestaflix_movies/112",
    telegramBotLink: "https://t.me/FiestaFlixBot?start=movie_12"
  }
];

export const tvShowsData: Movie[] = [
  {
    id: 101,
    title: "Dark Realms",
    year: 2025,
    genre: "Fantasy",
    rating: 9.2,
    narrator: "Rocky Kimomo",
    duration: "Season 1 (8 Eps)",
    quality: "1080p FHD",
    fileSize: "4.8 GB",
    contentType: 'series',
    seasonsCount: 1,
    episodesCount: 8,
    description: "Seven warlords contend for the Obsidian Throne while an ancient darkness creeps across the border mountains.",
    image: "/fallback-poster.png",
    backdrop: "/fallback-poster.png",
    telegramChannelPost: "https://t.me/fiestaflix_series/201",
    telegramBotLink: "https://t.me/FiestaFlixBot?start=series_101",
    episodes: [
      {
        id: "101-e1",
        seasonNumber: 1,
        episodeNumber: 1,
        title: "S1:E1 - The Bloodstone Ritual",
        duration: "52m",
        narrator: "Rocky Kimomo",
        description: "The ancient Obsidian portal begins glowing with violet fire as the first warlord gathers his knights.",
        thumbnail: "/fallback-poster.png",
        directStreamUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
        quality: "1080p FHD",
        fileSize: "620 MB",
      },
      {
        id: "101-e2",
        seasonNumber: 1,
        episodeNumber: 2,
        title: "S1:E2 - Whisperers in the Dark",
        duration: "48m",
        narrator: "Rocky Kimomo",
        description: "A traitor inside the high council steals the sacred cipher. Rocky brings heart-stopping suspense to the chase.",
        thumbnail: "/fallback-poster.png",
        directStreamUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
        quality: "1080p FHD",
        fileSize: "580 MB",
      },
      {
        id: "101-e3",
        seasonNumber: 1,
        episodeNumber: 3,
        title: "S1:E3 - The Siege of Karisimbi",
        duration: "55m",
        narrator: "Rocky Kimomo",
        description: "Northern mountain strongholds come under fire from mechanical flying drakes.",
        thumbnail: "/fallback-poster.png",
        directStreamUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
        quality: "1080p FHD",
        fileSize: "650 MB",
      },
      {
        id: "101-e4",
        seasonNumber: 1,
        episodeNumber: 4,
        title: "S1:E4 - The Obsidian Blade",
        duration: "50m",
        narrator: "Rocky Kimomo",
        description: "The hero forges a mystical weapon capable of cleaving shadows.",
        thumbnail: "/fallback-poster.png",
        directStreamUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
        quality: "1080p FHD",
        fileSize: "610 MB",
      },
      {
        id: "101-e5",
        seasonNumber: 1,
        episodeNumber: 5,
        title: "S1:E5 - Crown of Ash (Season Finale)",
        duration: "61m",
        narrator: "Rocky Kimomo",
        description: "The climactic battle atop the Obsidian mountain alters the fate of the seven realms forever.",
        thumbnail: "/fallback-poster.png",
        directStreamUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
        quality: "1080p FHD",
        fileSize: "740 MB",
      },
    ],
  },
  {
    id: 102,
    title: "City of Dreams",
    year: 2024,
    genre: "Drama",
    rating: 8.4,
    narrator: "Junior Giti",
    duration: "Season 2 (10 Eps)",
    quality: "1080p FHD",
    fileSize: "5.2 GB",
    contentType: 'series',
    seasonsCount: 2,
    episodesCount: 10,
    description: "Ambitious tech entrepreneurs and venture tycoons battle for supremacy in East Africa's fastest-growing silicon valley.",
    image: "/fallback-poster.png",
    backdrop: "/fallback-poster.png",
    telegramChannelPost: "https://t.me/fiestaflix_series/202",
    telegramBotLink: "https://t.me/FiestaFlixBot?start=series_102",
    episodes: [
      {
        id: "102-e1",
        seasonNumber: 2,
        episodeNumber: 1,
        title: "S2:E1 - High Stakes Pitch",
        duration: "44m",
        narrator: "Junior Giti",
        description: "A startup founder risks everything on a revolutionary satellite mesh protocol during a private Kigali gala.",
        thumbnail: "/fallback-poster.png",
        directStreamUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
        quality: "1080p FHD",
        fileSize: "520 MB",
      },
      {
        id: "102-e2",
        seasonNumber: 2,
        episodeNumber: 2,
        title: "S2:E2 - The Hostile Takeover",
        duration: "46m",
        narrator: "Junior Giti",
        description: "Boardroom betrayal leaves the founding team locked out of their own cloud servers.",
        thumbnail: "/fallback-poster.png",
        directStreamUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
        quality: "1080p FHD",
        fileSize: "540 MB",
      },
      {
        id: "102-e3",
        seasonNumber: 2,
        episodeNumber: 3,
        title: "S2:E3 - Midnight Code",
        duration: "42m",
        narrator: "Junior Giti",
        description: "Working from a hidden cafe in Kimihurura, an elite hacker launches a counter-intrusion.",
        thumbnail: "/fallback-poster.png",
        directStreamUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
        quality: "1080p FHD",
        fileSize: "510 MB",
      },
    ],
  },
  {
    id: 103,
    title: "Future Cop",
    year: 2025,
    genre: "Sci-Fi",
    rating: 8.9,
    narrator: "Savimbi",
    duration: "Season 1 (6 Eps)",
    quality: "4K UHD",
    fileSize: "6.5 GB",
    contentType: 'series',
    seasonsCount: 1,
    episodesCount: 6,
    description: "A cybernetically enhanced officer and an AI hologram navigate moral corruption in a lawless mega-district.",
    image: "/fallback-poster.png",
    backdrop: "/fallback-poster.png",
    telegramChannelPost: "https://t.me/fiestaflix_series/203",
    telegramBotLink: "https://t.me/FiestaFlixBot?start=series_103",
    episodes: [
      {
        id: "103-e1",
        seasonNumber: 1,
        episodeNumber: 1,
        title: "S1:E1 - Protocol Zero",
        duration: "50m",
        narrator: "Savimbi",
        description: "First patrol into the quarantined Neon Grid reveals synthetic weapons traded on the black market.",
        thumbnail: "/fallback-poster.png",
        directStreamUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
        quality: "4K UHD",
        fileSize: "890 MB",
      },
      {
        id: "103-e2",
        seasonNumber: 1,
        episodeNumber: 2,
        title: "S1:E2 - Ghost Signal",
        duration: "53m",
        narrator: "Savimbi",
        description: "An encrypted telemetry feed leads to a rogue android sanctuary beneath the city monorail.",
        thumbnail: "/fallback-poster.png",
        directStreamUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
        quality: "4K UHD",
        fileSize: "910 MB",
      },
    ],
  },
  {
    id: 104,
    title: "Family Ties",
    year: 2024,
    genre: "Comedy",
    rating: 7.9,
    narrator: "Dylan",
    duration: "Season 1 (12 Eps)",
    quality: "720p HD",
    fileSize: "3.2 GB",
    contentType: 'series',
    seasonsCount: 1,
    episodesCount: 12,
    description: "A boisterous extended family opens an eccentric fusion restaurant in downtown Kigali with laugh-out-loud mishaps.",
    image: "/fallback-poster.png",
    backdrop: "/fallback-poster.png",
    telegramChannelPost: "https://t.me/fiestaflix_series/204",
    telegramBotLink: "https://t.me/FiestaFlixBot?start=series_104",
    episodes: [
      {
        id: "104-e1",
        seasonNumber: 1,
        episodeNumber: 1,
        title: "S1:E1 - Grand Opening Chaos",
        duration: "30m",
        narrator: "Dylan",
        description: "Uncle Gaspard accidentally orders 500 crates of hot chili instead of plantains.",
        thumbnail: "/fallback-poster.png",
        directStreamUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
        quality: "720p HD",
        fileSize: "320 MB",
      },
    ],
  },
  {
    id: 105,
    title: "Spy Games",
    year: 2025,
    genre: "Thriller",
    rating: 8.7,
    narrator: "PK",
    duration: "Season 1 (8 Eps)",
    quality: "1080p FHD",
    fileSize: "4.9 GB",
    contentType: 'series',
    seasonsCount: 1,
    episodesCount: 8,
    description: "Counter-intelligence operatives play a deadly game of cat and mouse across five international capitals.",
    image: "/fallback-poster.png",
    backdrop: "/fallback-poster.png",
    telegramChannelPost: "https://t.me/fiestaflix_series/205",
    telegramBotLink: "https://t.me/FiestaFlixBot?start=series_105",
    episodes: [
      {
        id: "105-e1",
        seasonNumber: 1,
        episodeNumber: 1,
        title: "S1:E1 - The Courier in Nairobi",
        duration: "49m",
        narrator: "PK",
        description: "A mysterious hard drive must be transported past border security without triggering facial surveillance.",
        thumbnail: "/fallback-poster.png",
        directStreamUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
        quality: "1080p FHD",
        fileSize: "590 MB",
      },
    ],
  },
  {
    id: 106,
    title: "Wild Nature",
    year: 2024,
    genre: "Documentary",
    rating: 9.0,
    narrator: "Gaheza",
    duration: "Season 1 (5 Eps)",
    quality: "4K UHD",
    fileSize: "7.1 GB",
    contentType: 'series',
    seasonsCount: 1,
    episodesCount: 5,
    description: "Breathtaking cinematography tracing the endangered mountain gorillas of the Virunga volcanoes and savannah wildlife.",
    image: "/fallback-poster.png",
    backdrop: "/fallback-poster.png",
    telegramChannelPost: "https://t.me/fiestaflix_series/206",
    telegramBotLink: "https://t.me/FiestaFlixBot?start=series_106",
    episodes: [
      {
        id: "106-e1",
        seasonNumber: 1,
        episodeNumber: 1,
        title: "S1:E1 - Keepers of the Mist",
        duration: "52m",
        narrator: "Gaheza",
        description: "The silverback alpha leads his family through ancient bamboo forests as dawn breaks over the volcanic slopes.",
        thumbnail: "/fallback-poster.png",
        directStreamUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
        quality: "4K UHD",
        fileSize: "920 MB",
      },
    ],
  },
];

export function getAllCatalogContent(): Movie[] {
  const moviesWithContentType: Movie[] = movieData.map((m) => ({
    ...m,
    contentType: 'movie' as const,
  }));
  const baseCatalog = [...moviesWithContentType, ...tvShowsData];
  const baseTitles = new Set(baseCatalog.map((m) => m.title.toLowerCase().trim()));

  let csvMovies: Movie[] = [];
  try {
    csvMovies = loadCsvCatalog().filter(
      (m) => !baseTitles.has(m.title.toLowerCase().trim())
    );
  } catch (err) {
    console.warn('[movieData] Could not load csvCatalog:', err);
  }

  return [...baseCatalog, ...csvMovies];
}

export function findMovieOrSeries(id: string | number): Movie | undefined {
  const all = getAllCatalogContent();
  const idStr = String(id).toLowerCase();
  return all.find(
    (item) =>
      String(item.id).toLowerCase() === idStr ||
      item.title.toLowerCase().replace(/[^a-z0-9]+/g, '-') === idStr
  );
}
