import fs from 'fs';
import path from 'path';

const rawData = `The End of Oak Street	After a mysterious cosmic event rips Oak Street from suburbia and transports their neighborhood into a prehistoric rainforest, the Platt family must fight prehistoric beasts to survive.	Gaheza Simba	Sci-Fi, Adventure, Horror	6600	2026	https://www.mediafire.com/file/an9kagqqh01yto8/End_Of_The_Oak_Street.mp4/file	https://image.tmdb.org/t/p/w500/mK9k2tW6D7vD9O9w500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Knights of the Zodiac - Part A	When a goddess of war reincarnates in the body of a young girl, street orphan Seiya discovers that he is destined to protect her and save the world.	Gaheza Simba	Action, Adventure, Fantasy	3360	2023	https://www.mediafire.com/file/qvgw90uyce03uzm/Knights_of_the_Zodiac_A.mp4/file	https://image.tmdb.org/t/p/w500/qW4crfED8mpNDadSmMdi7Spzh9X.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Knights of the Zodiac - Part B	When a goddess of war reincarnates in the body of a young girl, street orphan Seiya discovers that he is destined to protect her and save the world.	Gaheza Simba	Action, Adventure, Fantasy	3360	2023	https://www.mediafire.com/file/2sjfobw6j2rm4ui/Knights_of_the_Zodiac_B.mp4/file	https://image.tmdb.org/t/p/w500/qW4crfED8mpNDadSmMdi7Spzh9X.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Moana (2026)	Leaving her island for the first time, young Moana embarks on an epic seafaring adventure to restore prosperity to her people.	Gaheza Simba	Animation, Adventure, Family	6420	2026	https://www.mediafire.com/file/nz6f9kwm726alxe/MOANA_2026.mp4/file	https://image.tmdb.org/t/p/w500/4YZpsylmjHbqeWzjKpUEF8gcLUV.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Ready or Not 2	A bride's wedding night takes a horrific turn when her eccentric in-laws force her to take part in a terrifying survival ritual.	Gaheza Simba	Comedy, Horror, Mystery	5700	2026	https://www.mediafire.com/file/bh1udp098bfeuod/READY_OR_NOT_2_.mp4/file	https://image.tmdb.org/t/p/w500/vOl6LmNu2ocZhYuIAOh93DNqh9o.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
From Paris with Love	In Paris, a young employee in the office of the US Ambassador hooks up with an unorthodox American spy looking to stop a terrorist attack.	Gaheza Simba	Action, Crime, Thriller	5520	2010	https://www.mediafire.com/file/mrcnsj8pxkqoerf/FROM_PARIS_WITH_LOVE_FULL.mp4/file	https://image.tmdb.org/t/p/w500/hP5e5d1uLgL6UeZJzIuQ0zQ1zZ1.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
In the Grey	When a ruthless despot steals a billion-dollar fortune, a team of elite covert operatives is dispatched to steal it back.	Gaheza Simba	Action, Thriller	6300	2026	https://www.mediafire.com/file/l5bfjq4r0nlpumo/IN_THE_GREY.mp4/file	https://image.tmdb.org/t/p/w500/inTheGrey2026PosterPath500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
The Maze Runner	Thomas is deposited in a community of boys after his memory is erased, soon learning they're all trapped in a maze that will require him to join forces with fellow runners for a shot at escape.	Gaheza Simba	Action, Mystery, Sci-Fi	6780	2014	https://www.mediafire.com/file/v2ns8pxqpqslhqa/THE_MAZE_RUNNER.mp4/file	https://image.tmdb.org/t/p/w500/ode14q7WtDugFDp78fo9lCsmay9.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
xXx: Return of Xander Cage	Xander Cage is left for dead after an incident, though he secretly returns to action for a new, tough assignment with his handler Augustus Gibbons.	Gaheza Simba	Action, Adventure, Thriller	6420	2017	https://www.mediafire.com/file/txya9zvgf3yprpq/xXx_the_return_of_xander_cage.mp4/file	https://image.tmdb.org/t/p/w500/xe70rY1uomDoo475a89uwh245Z7.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Hidden Strike	Two former special forces soldiers must escort a group of civilians along Baghdad's 'Highway of Death' to the safety of the Green Zone.	Gaheza Simba	Action, Adventure, Comedy	6180	2023	https://www.mediafire.com/file/opv4k9wjjivmv0n/Hidden_Strike_Hd.mp4/file	https://image.tmdb.org/t/p/w500/zs2ecOqYqsaViP96a7Hn0M4iP0.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Day Shift - Part A	A hard-working, blue-collar dad just wants to provide a good life for his quick-witted 10-year-old daughter, using a pool cleaning job as a front for his real work: hunting vampires.	Gaheza Simba	Action, Comedy, Fantasy	3390	2022	https://www.mediafire.com/file/e49g5du2sbhd5v1/Day_Shift_A.mp4/file	https://image.tmdb.org/t/p/w500/9eAnMtqvzJ7YCE4eaCGfsa0E296.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Day Shift - Part B	A hard-working, blue-collar dad just wants to provide a good life for his quick-witted 10-year-old daughter, using a pool cleaning job as a front for his real work: hunting vampires.	Gaheza Simba	Action, Comedy, Fantasy	3390	2022	https://www.mediafire.com/file/yajkdizgz2ljdtu/Day_Shift_B.mp4/file	https://image.tmdb.org/t/p/w500/9eAnMtqvzJ7YCE4eaCGfsa0E296.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Deep Water	A well-to-do husband who allows his wife to have affairs in order to avoid a divorce becomes a prime suspect in the disappearance of her lovers.	Gaheza Simba	Drama, Mystery, Thriller	6900	2022	https://www.mediafire.com/file/pk60hbl8q6yryv5/DEEP_WATER.mp4/file	https://image.tmdb.org/t/p/w500/kb4n6Op899p8k9L80f55h11p0pL.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Mortal Kombat 2	Earthrealm champions join forces with iconic warriors across realms to battle Shao Kahn and the forces of Outworld in the tournament.	Gaheza Simba	Action, Adventure, Fantasy	6600	2025	https://www.mediafire.com/file/tmpoxqbjvh2j1ib/MORTAL_KOMBAT_2.mp4/file	https://image.tmdb.org/t/p/w500/mortalKombat2Poster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Seven Snipers	A retired elite sniper reunites with her former crew to protect her daughter from a vengeful warlord's wrath across the Australian Outback.	Gaheza Simba	Action, Thriller	5220	2026	https://www.mediafire.com/file/ia4o0n5dp743w1b/SEVEN_SNIPERS_%25281%2529.mp4/file	https://image.tmdb.org/t/p/w500/sevenSnipersPoster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Apex	Six elite hunters pay to hunt a man on a deserted island, only to find themselves becoming the prey when he fights back.	Gaheza Simba	Action, Sci-Fi, Thriller	5640	2021	https://www.mediafire.com/file/99wrfog0c9n9ayz/APEX_BY_GAHEZA%252B2026%252B.mp4/file	https://image.tmdb.org/t/p/w500/apexPosterPath500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Beast	A father and his two teenage daughters find themselves hunted by a massive rogue lion intent on proving that the Savanna has but one apex predator.	Gaheza Simba	Action, Drama, Horror	5580	2022	https://www.mediafire.com/file/q6t54wtgsjhhdfp/Beast_2026_Hd.mp4/file	https://image.tmdb.org/t/p/w500/beastPosterPath500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Close	A counter-terrorism expert takes a job protecting a young heiress. After an attempted kidnapping, both are forced to go on the run.	Gaheza Simba	Action, Thriller	5640	2019	https://www.mediafire.com/file/jype48vg1819ukd/Close_Gaheza_Full.mp4/file	https://image.tmdb.org/t/p/w500/closePosterPath500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
War Machine	A recruit in an elite special forces training unit leads a survival squad against an unexpected and heavily armed extraterrestrial machine threat.	Gaheza Simba	Action, Sci-Fi	6420	2026	https://www.mediafire.com/file/4jj0kdnd2l7zgpr/WAR_MACHINE.mp4/file	https://image.tmdb.org/t/p/w500/warMachine2026Poster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Avatar: The Way of Water - Part A	Jake Sully lives with his newfound family formed on the extrasolar moon Pandora. Once a familiar threat returns to finish what was previously started, Jake must work with Neytiri and the army of the Na'vi race to protect their home.	Gaheza Simba	Action, Adventure, Fantasy	5760	2022	https://www.mediafire.com/file/6py5p5c0rrwnhqy/Avatar_2_Way_Of_Water_A.mp4/file	https://image.tmdb.org/t/p/w500/t6HIqrRAclMCA60NsSmeqe9RmNV.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Avatar: The Way of Water - Part B	Jake Sully lives with his newfound family formed on the extrasolar moon Pandora. Once a familiar threat returns to finish what was previously started, Jake must work with Neytiri and the army of the Na'vi race to protect their home.	Gaheza Simba	Action, Adventure, Fantasy	5760	2022	https://www.mediafire.com/file/tb9l7pcatevell1/Avatar_The_Way_Of_Water_B.mp4/file	https://image.tmdb.org/t/p/w500/t6HIqrRAclMCA60NsSmeqe9RmNV.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
The Ice Road 2: Road to the Sky	Mike McCann travels to Nepal to scatter his late brother's ashes on Mt. Everest, only to find himself and his guide confronting dangerous mercenaries on a tour bus.	Gaheza Simba	Action, Adventure, Thriller	6300	2025	https://www.mediafire.com/file/a6yj80u8su20i56/ICE_ROAD_2_VEGEANCE.MP4/file	https://image.tmdb.org/t/p/w500/iceRoad2Poster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
The Ice Road	After a remote diamond mine collapses in far northern Canada, a 'big-rig' ice road driver must lead an impossible rescue mission over a frozen lake to save the trapped miners.	Gaheza Simba	Action, Adventure, Thriller	6540	2021	https://www.mediafire.com/file/057xnjd167sotrn/ICE_ROAD.mp4/file	https://image.tmdb.org/t/p/w500/eWW0t42FzVj67bT3eQzH0oK0k45.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Mufasa: The Lion King	Mufasa, a cub lost and alone, meets a sympathetic lion named Taka, the heir to a royal bloodline. The chance meeting sets in motion an expansive journey of a group of misfits looking for their destiny.	Gaheza Simba	Animation, Adventure, Drama	7080	2024	https://www.mediafire.com/file/y9mx0bstc9lso8d/MUFASA_THE_LION_KING.mp4/file	https://image.tmdb.org/t/p/w500/mufasaLionKingPoster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Angels Fallen: Warriors of Peace	An Iraq War veteran receives a calling from higher powers to assemble a team of supernatural warriors and save the world from an impending demonic army.	Gaheza Simba	Action, Adventure, Fantasy	5880	2024	https://www.mediafire.com/file/rfcrazct41wgdwc/Angels_Fallen_Warriors_Of_Peace.mp4/file	https://image.tmdb.org/t/p/w500/angelsFallen2Poster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Ready or Not - Part A	A bride's wedding night takes a sinister turn when her eccentric, new in-laws force her to take part in a terrifying game.	Gaheza Simba	Action, Comedy, Horror	2850	2019	https://www.mediafire.com/file/bcyslnuojuqppou/READY_OR_NOT_A.mp4/file	https://image.tmdb.org/t/p/w500/vOl6LmNu2ocZhYuIAOh93DNqh9o.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Ready or Not - Part B	A bride's wedding night takes a sinister turn when her eccentric, new in-laws force her to take part in a terrifying game.	Gaheza Simba	Action, Comedy, Horror	2850	2019	https://www.mediafire.com/file/um1277zhcpvmah1/READY_OR_NOT_B.mp4/file	https://image.tmdb.org/t/p/w500/vOl6LmNu2ocZhYuIAOh93DNqh9o.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
World War Z - Part A	Former United Nations employee Gerry Lane traverses the world in a race against time to stop a zombie pandemic that is toppling armies and governments and threatening to destroy humanity itself.	Gaheza Simba	Action, Adventure, Sci-Fi	3480	2013	https://drive.google.com/file/d/1Ao9ybl69HX_xYthWZW9bHX5EwKsunw9P/view?usp=sharing	https://image.tmdb.org/t/p/w500/1SWBflCgnNDVwLKm4fHnFj8V87F.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
World War Z - Part B	Former United Nations employee Gerry Lane traverses the world in a race against time to stop a zombie pandemic that is toppling armies and governments and threatening to destroy humanity itself.	Gaheza Simba	Action, Adventure, Sci-Fi	3480	2013	https://drive.google.com/file/d/1E3UekdWZ1DaDePtMpu4Wy0YotQEJh1RV/view?usp=sharing	https://image.tmdb.org/t/p/w500/1SWBflCgnNDVwLKm4fHnFj8V87F.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Kal Ho Naa Ho - Part A	Naina, an introverted, depressed girl's life changes when she meets Aman. But Aman has a secret of his own which changes their lives forever. Embroiled in all this is Rohit, Naina's best friend who conceals his love for her.	Junior Giti	Comedy, Drama, Musical, Romance	5600	2003	https://www.mediafire.com/file/gk8jvf9s0s3chl5/Kal_Ho_Naa_Ho_A_Hd.mp4/file	https://image.tmdb.org/t/p/w500/yvM3M0hJ9J1aH2h182QzYxMh500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Kal Ho Naa Ho - Part B	Naina, an introverted, depressed girl's life changes when she meets Aman. But Aman has a secret of his own which changes their lives forever. Embroiled in all this is Rohit, Naina's best friend who conceals his love for her.	Junior Giti	Comedy, Drama, Musical, Romance	5600	2003	https://www.mediafire.com/file/13dswq5xqxv96tu/Kal_Ho_Naa_Ho_B_Hd.mp4/file	https://image.tmdb.org/t/p/w500/yvM3M0hJ9J1aH2h182QzYxMh500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Kuch Kuch Hota Hai - Part A	During their college years, Anjali was in love with her best-friend Rahul, but he had eyes only for Tina. Years later, Rahul's now-eight-year-old daughter attempts to reunite her father and Anjali.	Junior Giti	Comedy, Drama, Musical, Romance	5550	1998	https://www.mediafire.com/file/6wqo5yv9bwac6c5/Kuch_Kuch_Hota_Hai_A_.mp4/file	https://image.tmdb.org/t/p/w500/kkhhPosterPath500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Kuch Kuch Hota Hai - Part B	During their college years, Anjali was in love with her best-friend Rahul, but he had eyes only for Tina. Years later, Rahul's now-eight-year-old daughter attempts to reunite her father and Anjali.	Junior Giti	Comedy, Drama, Musical, Romance	5550	1998	https://www.mediafire.com/file/7jkgwmzmaoovsjm/Kuch_Kuch_Hota_Hai-720P.mp4/file	https://image.tmdb.org/t/p/w500/kkhhPosterPath500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Indemnity	An ex-firefighter in Cape Town with severe PTSD is framed for the murder of his wife and flees through the city, unraveling a high-level government conspiracy.	Junior Giti	Action, Crime, Thriller	7440	2021	https://www.mediafire.com/file/y9jhous2684hn6l/Watch_Indeminity_%25282021%2529_1.mp4/file	https://image.tmdb.org/t/p/w500/indemnity2021Poster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Ip Man 4: The Finale	The Kung Fu master travels to the U.S. where his student Bruce Lee has upset the local martial arts community by opening a Wing Chun school.	Junior Giti	Action, Biography, Drama	6300	2019	https://www.mediafire.com/file/quh3siqd6vte5bx/Ip_Man_4_Hd.mp4/file	https://image.tmdb.org/t/p/w500/ipMan4Poster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Ip Man 3	When a band of brutal gangsters led by a crooked property developer try to take over a local school, Master Ip is forced to take a stand.	Junior Giti	Action, Biography, Drama	6300	2015	https://www.mediafire.com/file/ya9qjuaif453gzn/Ip_Man_3_Hd.mp4/file	https://image.tmdb.org/t/p/w500/ipMan3Poster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Chinese Zodiac (CZ12)	Asian Hawk leads a mercenary team to recover twelve bronze head artifacts of the Chinese zodiac animals, which were looted from the Old Summer Palace in 1860.	Junior Giti	Action, Adventure, Comedy	7380	2012	https://www.mediafire.com/file/f7xpspeao0hz4sx/Chinese_Zodiac-Hd.mp4/file	https://image.tmdb.org/t/p/w500/cz12Poster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Iceman: The Time Traveler	The imperial guard and his three treacherous childhood friends ordered to hunt him down get accidentally buried and kept frozen in time for 400 years.	Junior Giti	Action, Comedy, History, Sci-Fi	5220	2018	https://www.mediafire.com/file/7tvnhmthm4bxim7/Iceman-_The_Time_Traveler_Hd.mp4/file	https://image.tmdb.org/t/p/w500/icemanTimeTravelerPoster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
The Witch: Part 1. The Subversion	A high school student with amnesia tries to uncover what happened to her after strange people begin appearing in her life and causing havoc.	Junior Giti	Action, Mystery, Sci-Fi, Thriller	7500	2018	https://www.mediafire.com/file/g9n9sbg5nrq5f88/The_Witch_Part_1_-_The_Subversion_Hd.mp4/file	https://image.tmdb.org/t/p/w500/theWitchPart1Poster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Peter Rabbit	Feature adaptation of Beatrix Potter's classic tale of a rebellious rabbit trying to sneak into a farmer's vegetable garden.	Junior Giti	Animation, Adventure, Comedy	5700	2018	https://www.mediafire.com/file/04xw0iw481y2vwk/Peter_Rabbit_Hd.mp4/file	https://image.tmdb.org/t/p/w500/peterRabbitPoster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Buffalo Boys	In 19th-century Java, two exiled brothers return from America to avenge the brutal death of their parents at the hands of a Dutch colonial tyrant.	Junior Giti	Action, Western	6120	2018	https://www.mediafire.com/file/rq2ysklb22n69ws/Buffalo_Boy_Hd.mp4/file	https://image.tmdb.org/t/p/w500/buffaloBoysPoster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Bad Genius - Part A	Lynn, a genius high school student who makes money cheating on tests, receives a new task that leads her to Sydney, Australia to stage an international exam heist.	Junior Giti	Comedy, Crime, Drama, Thriller	3900	2017	https://www.mediafire.com/file/e2evg0emz8v8eev/Bad_Genius_A_Hd_Mp4.mp4/file	https://image.tmdb.org/t/p/w500/badGeniusPoster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Bad Genius - Part B	Lynn, a genius high school student who makes money cheating on tests, receives a new task that leads her to Sydney, Australia to stage an international exam heist.	Junior Giti	Comedy, Crime, Drama, Thriller	3900	2017	https://www.mediafire.com/file/b7p3tt8qp45fp4s/Bad_Genius_B_Hd_Mp4.mp4/file	https://image.tmdb.org/t/p/w500/badGeniusPoster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Nobody - Part A	A docile family man slowly reveals his true character after his house is burgled by two petty thieves, which, coincidentally, leads him into a bloody war with a Russian crime boss.	Junior Giti	Action, Crime, Thriller	2760	2021	https://www.mediafire.com/file/b39k7q3usf13b25/NO_BODY_A.mp4/file	https://image.tmdb.org/t/p/w500/oBgWY00bEFeZ9N25wWVyuQddbBc.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Nobody - Part B	A docile family man slowly reveals his true character after his house is burgled by two petty thieves, which, coincidentally, leads him into a bloody war with a Russian crime boss.	Junior Giti	Action, Crime, Thriller	2760	2021	https://www.mediafire.com/file/mv14ptyqmw72vmd/NO_BODY_B.mp4/file	https://image.tmdb.org/t/p/w500/oBgWY00bEFeZ9N25wWVyuQddbBc.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com`;

const lines = rawData.trim().split('\n');
const csvLines = lines.map(line => {
  const parts = line.split('\t');
  return parts.map(p => `"${(p || '').trim().replace(/"/g, '""')}"`).join(',');
});

const targetPath = path.join(process.cwd(), 'movies.csv');
fs.appendFileSync(targetPath, '\n' + csvLines.join('\n'));
console.log(`Appended ${csvLines.length} movie records to movies.csv`);
