import fs from 'fs';
import path from 'path';

const rawData = `My Country: The New Age Ep 01	Set during the end of the Goryeo period into the early Joseon period, two friends become enemies due to differences in opinion about their country.	Junior Giti	Action, Drama, History, Romance	4200	2019	https://www.mediafire.com/file/baioth2p4ucfi4u/My_Country_Ep1_Hd.mp4/file	https://image.tmdb.org/t/p/w500/myCountryNewAgePoster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
My Country: The New Age Ep 02	Set during the end of the Goryeo period into the early Joseon period, two friends become enemies due to differences in opinion about their country.	Junior Giti	Action, Drama, History, Romance	4200	2019	https://www.mediafire.com/file/ods9k21m7k008aa/My_Country_E02_Hd.Mp4.mp4/file	https://image.tmdb.org/t/p/w500/myCountryNewAgePoster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
My Country: The New Age Ep 03	Set during the end of the Goryeo period into the early Joseon period, two friends become enemies due to differences in opinion about their country.	Junior Giti	Action, Drama, History, Romance	4200	2019	https://www.mediafire.com/file/q8zvfvjdx5bomzq/My_Country_E03_Hd.mp4/file	https://image.tmdb.org/t/p/w500/myCountryNewAgePoster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
My Country: The New Age Ep 04	Set during the end of the Goryeo period into the early Joseon period, two friends become enemies due to differences in opinion about their country.	Junior Giti	Action, Drama, History, Romance	4200	2019	https://www.mediafire.com/file/vs8wr5merflrs4x/My.Country_Ep4.in%25C2%25B4.mp4/file	https://image.tmdb.org/t/p/w500/myCountryNewAgePoster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
My Country: The New Age Ep 05	Set during the end of the Goryeo period into the early Joseon period, two friends become enemies due to differences in opinion about their country.	Junior Giti	Action, Drama, History, Romance	4200	2019	https://www.mediafire.com/file/rasuas2b86ic5nk/My_Country_E05_Hd.mp4/file	https://image.tmdb.org/t/p/w500/myCountryNewAgePoster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
My Country: The New Age Ep 06	Set during the end of the Goryeo period into the early Joseon period, two friends become enemies due to differences in opinion about their country.	Junior Giti	Action, Drama, History, Romance	4200	2019	https://www.mediafire.com/file/nkuebh3r9lxmrhp/My_Countrry_E06_Hd.mp4/file	https://image.tmdb.org/t/p/w500/myCountryNewAgePoster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
My Country: The New Age Ep 07	Set during the end of the Goryeo period into the early Joseon period, two friends become enemies due to differences in opinion about their country.	Junior Giti	Action, Drama, History, Romance	4200	2019	https://www.mediafire.com/file/jjdt6nlknedfnui/My_Country_E07_Hd.mp4/file	https://image.tmdb.org/t/p/w500/myCountryNewAgePoster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
My Country: The New Age Ep 08	Set during the end of the Goryeo period into the early Joseon period, two friends become enemies due to differences in opinion about their country.	Junior Giti	Action, Drama, History, Romance	4200	2019	https://www.mediafire.com/file/etyx5yrgrcnylus/My_Country_E08_Hd.mp4/file	https://image.tmdb.org/t/p/w500/myCountryNewAgePoster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
My Country: The New Age Ep 09	Set during the end of the Goryeo period into the early Joseon period, two friends become enemies due to differences in opinion about their country.	Junior Giti	Action, Drama, History, Romance	4200	2019	https://www.mediafire.com/file/le8jodpc40883dk/My_Country_E09_Hd.mp4/file	https://image.tmdb.org/t/p/w500/myCountryNewAgePoster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
My Country: The New Age Ep 10	Set during the end of the Goryeo period into the early Joseon period, two friends become enemies due to differences in opinion about their country.	Junior Giti	Action, Drama, History, Romance	4200	2019	https://www.mediafire.com/file/eyfuajenoiyw9j3/My_Country_E010_Hd.mp4/file	https://image.tmdb.org/t/p/w500/myCountryNewAgePoster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
My Country: The New Age Ep 11	Set during the end of the Goryeo period into the early Joseon period, two friends become enemies due to differences in opinion about their country.	Junior Giti	Action, Drama, History, Romance	4200	2019	https://www.mediafire.com/file/d8ylrkxoag537ij/My_Country_E011_Hd.mp4/file	https://image.tmdb.org/t/p/w500/myCountryNewAgePoster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
My Country: The New Age Ep 12	Set during the end of the Goryeo period into the early Joseon period, two friends become enemies due to differences in opinion about their country.	Junior Giti	Action, Drama, History, Romance	4200	2019	https://www.mediafire.com/file/22jglypuwwt4htd/My_Country_E012_Hd.mp4/file	https://image.tmdb.org/t/p/w500/myCountryNewAgePoster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
My Country: The New Age Ep 13	Set during the end of the Goryeo period into the early Joseon period, two friends become enemies due to differences in opinion about their country.	Junior Giti	Action, Drama, History, Romance	4200	2019	https://www.mediafire.com/file/omfsjxalnbfeu48/My_Country_E013_Hd.mp4/file	https://image.tmdb.org/t/p/w500/myCountryNewAgePoster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
My Country: The New Age Ep 14	Set during the end of the Goryeo period into the early Joseon period, two friends become enemies due to differences in opinion about their country.	Junior Giti	Action, Drama, History, Romance	4200	2019	https://www.mediafire.com/file/plxvqhgmlh5mrly/My_Country_E014_Hd.mp4/file	https://image.tmdb.org/t/p/w500/myCountryNewAgePoster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
My Country: The New Age Ep 15	Set during the end of the Goryeo period into the early Joseon period, two friends become enemies due to differences in opinion about their country.	Junior Giti	Action, Drama, History, Romance	4200	2019	https://www.mediafire.com/file/law1nov7l53h7ho/My_Country_E015_Hd.mp4/file	https://image.tmdb.org/t/p/w500/myCountryNewAgePoster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
My Country: The New Age Ep 16 Final	Set during the end of the Goryeo period into the early Joseon period, two friends become enemies due to differences in opinion about their country.	Junior Giti	Action, Drama, History, Romance	4200	2019	https://www.mediafire.com/file/msjuptumtqosqk1/My_Country_E016_Final_Hd.mp4/file	https://image.tmdb.org/t/p/w500/myCountryNewAgePoster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Six S01 Ep 1	Navy SEAL Team Six attempts to eliminate a Taliban leader in Afghanistan when they discover an American citizen working with the enemy.	Junior Giti	Action, Drama, History, War	2580	2017	https://www.mediafire.com/file/aiu88c6jdyjkp85/Six_Ep1hd.mp4_2.mp4/file	https://image.tmdb.org/t/p/w500/sixHistoryChannelPoster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Six S01 Ep 2	Navy SEAL Team Six attempts to eliminate a Taliban leader in Afghanistan when they discover an American citizen working with the enemy.	Junior Giti	Action, Drama, History, War	2580	2017	https://www.mediafire.com/file/oaq64uheysy4ivo/Six_Ep2_Hd.mp4.mp4/file	https://image.tmdb.org/t/p/w500/sixHistoryChannelPoster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Six S01 Ep 3	Navy SEAL Team Six attempts to eliminate a Taliban leader in Afghanistan when they discover an American citizen working with the enemy.	Junior Giti	Action, Drama, History, War	2580	2017	https://www.mediafire.com/file/kz4in7ocpfbf4ek/Six_Ep3_Hd.mp4.mp4/file	https://image.tmdb.org/t/p/w500/sixHistoryChannelPoster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Six S01 Ep 4	Navy SEAL Team Six attempts to eliminate a Taliban leader in Afghanistan when they discover an American citizen working with the enemy.	Junior Giti	Action, Drama, History, War	2580	2017	https://www.mediafire.com/file/n7zy7k1a2hlvymq/Six_S01_Ep4_Hd.mp4/file	https://image.tmdb.org/t/p/w500/sixHistoryChannelPoster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Six S01 Ep 5	Navy SEAL Team Six attempts to eliminate a Taliban leader in Afghanistan when they discover an American citizen working with the enemy.	Junior Giti	Action, Drama, History, War	2580	2017	https://www.mediafire.com/file/u1qe20mvi0yj2eh/Six_S01_Ep5_Hd.mp4/file	https://image.tmdb.org/t/p/w500/sixHistoryChannelPoster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Six S01 Ep 6	Navy SEAL Team Six attempts to eliminate a Taliban leader in Afghanistan when they discover an American citizen working with the enemy.	Junior Giti	Action, Drama, History, War	2580	2017	https://www.mediafire.com/file/eizqkjjxrk20lnk/Six_S01_Ep6_Hd.mp4/file	https://image.tmdb.org/t/p/w500/sixHistoryChannelPoster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Six S01 Ep 7	Navy SEAL Team Six attempts to eliminate a Taliban leader in Afghanistan when they discover an American citizen working with the enemy.	Junior Giti	Action, Drama, History, War	2580	2017	https://www.mediafire.com/file/x6pltg02erruywq/Six_S01_Ep7_Hd.mp4/file	https://image.tmdb.org/t/p/w500/sixHistoryChannelPoster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Six S01 Ep 8 Final	Navy SEAL Team Six attempts to eliminate a Taliban leader in Afghanistan when they discover an American citizen working with the enemy.	Junior Giti	Action, Drama, History, War	2580	2017	https://www.mediafire.com/file/k1g9hongv8rypew/Six_S1_Ep8_Final_Hd.mp4/file	https://image.tmdb.org/t/p/w500/sixHistoryChannelPoster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
The Polygamist Ep 01	A complex web of traditional expectations, jealousy, and fierce ambition ensues when a wealthy patriarch balances multiple households under one roof.	Junior Giti	Drama, Romance	2700	2026	https://www.mediafire.com/file/1kk2y0epkwu5eid/Polygamist_2026_Ep1.mp4/file	https://image.tmdb.org/t/p/w500/polygamist2026Poster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
The Polygamist Ep 02	A complex web of traditional expectations, jealousy, and fierce ambition ensues when a wealthy patriarch balances multiple households under one roof.	Junior Giti	Drama, Romance	2700	2026	https://www.mediafire.com/file/43ehwbdcohd7uvp/Polygamist_2026_Ep2.mp4/file	https://image.tmdb.org/t/p/w500/polygamist2026Poster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
The Polygamist Ep 03	A complex web of traditional expectations, jealousy, and fierce ambition ensues when a wealthy patriarch balances multiple households under one roof.	Junior Giti	Drama, Romance	2700	2026	https://www.mediafire.com/file/t8w5v9yx7i0l1t1/Polygamist_%25282026%2529_Ep3.mp4/file	https://image.tmdb.org/t/p/w500/polygamist2026Poster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
The Polygamist Ep 04	A complex web of traditional expectations, jealousy, and fierce ambition ensues when a wealthy patriarch balances multiple households under one roof.	Junior Giti	Drama, Romance	2700	2026	https://www.mediafire.com/file/7uettxr0vttbco9/Polygamist_%25282026%2529_Ep4.mp4/file	https://image.tmdb.org/t/p/w500/polygamist2026Poster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
The Polygamist Ep 05	A complex web of traditional expectations, jealousy, and fierce ambition ensues when a wealthy patriarch balances multiple households under one roof.	Junior Giti	Drama, Romance	2700	2026	https://www.mediafire.com/file/y17y384buxuo83i/Polygamist_%25282026%2529_Ep5.mp4/file	https://image.tmdb.org/t/p/w500/polygamist2026Poster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
The Polygamist Ep 06	A complex web of traditional expectations, jealousy, and fierce ambition ensues when a wealthy patriarch balances multiple households under one roof.	Junior Giti	Drama, Romance	2700	2026	https://www.mediafire.com/file/qnj8hzh6xz2f8t5/Polygamist_%25282026%2529_Ep6.mp4/file	https://image.tmdb.org/t/p/w500/polygamist2026Poster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
The Polygamist Ep 07	A complex web of traditional expectations, jealousy, and fierce ambition ensues when a wealthy patriarch balances multiple households under one roof.	Junior Giti	Drama, Romance	2700	2026	https://www.mediafire.com/file/i6m9ehlmi13dikh/Polygamist_%25282026%2529_Ep7.mp4/file	https://image.tmdb.org/t/p/w500/polygamist2026Poster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
The Polygamist Ep 08	A complex web of traditional expectations, jealousy, and fierce ambition ensues when a wealthy patriarch balances multiple households under one roof.	Junior Giti	Drama, Romance	2700	2026	https://www.mediafire.com/file/fwiv52qk5hknunh/Polygamist_%25282026%2529_Ep8.mp4/file	https://image.tmdb.org/t/p/w500/polygamist2026Poster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
The Polygamist Ep 09	A complex web of traditional expectations, jealousy, and fierce ambition ensues when a wealthy patriarch balances multiple households under one roof.	Junior Giti	Drama, Romance	2700	2026	https://www.mediafire.com/file/4sxoq3zrs8nyan7/Polygamist_%25282026%2529_Ep9.mp4/file	https://image.tmdb.org/t/p/w500/polygamist2026Poster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
The Polygamist Ep 10	A complex web of traditional expectations, jealousy, and fierce ambition ensues when a wealthy patriarch balances multiple households under one roof.	Junior Giti	Drama, Romance	2700	2026	https://www.mediafire.com/file/xtfe67k2d97nhs8/Polygamist_%25282026%2529_ep10.mp4/file	https://image.tmdb.org/t/p/w500/polygamist2026Poster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
The Polygamist Ep 11	A complex web of traditional expectations, jealousy, and fierce ambition ensues when a wealthy patriarch balances multiple households under one roof.	Junior Giti	Drama, Romance	2700	2026	https://www.mediafire.com/file/7gyhkwf1y4xvf6q/Polygamist_%25282026%2529_Ep11.mp4/file	https://image.tmdb.org/t/p/w500/polygamist2026Poster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
The Polygamist Ep 12	A complex web of traditional expectations, jealousy, and fierce ambition ensues when a wealthy patriarch balances multiple households under one roof.	Junior Giti	Drama, Romance	2700	2026	https://www.mediafire.com/file/0dxzptvdkexw26q/Polygamist_%25282026%2529_Ep12.mp4/file	https://image.tmdb.org/t/p/w500/polygamist2026Poster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
The Polygamist Ep 13	A complex web of traditional expectations, jealousy, and fierce ambition ensues when a wealthy patriarch balances multiple households under one roof.	Junior Giti	Drama, Romance	2700	2026	https://www.mediafire.com/file/vd0oy2ulbak936e/Polygamist_%25282026%2529_Ep13.mp4/file	https://image.tmdb.org/t/p/w500/polygamist2026Poster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
The Polygamist Ep 14	A complex web of traditional expectations, jealousy, and fierce ambition ensues when a wealthy patriarch balances multiple households under one roof.	Junior Giti	Drama, Romance	2700	2026	https://www.mediafire.com/file/lcpoz1ngtolmega/Polygamist_%25282026%2529_Ep14.mp4/file	https://image.tmdb.org/t/p/w500/polygamist2026Poster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
The Polygamist Ep 15	A complex web of traditional expectations, jealousy, and fierce ambition ensues when a wealthy patriarch balances multiple households under one roof.	Junior Giti	Drama, Romance	2700	2026	https://www.mediafire.com/file/ll219b6xy0ojv5l/Polygamist_%25282026%2529_Ep15.mp4/file	https://image.tmdb.org/t/p/w500/polygamist2026Poster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
The Polygamist Ep 16	A complex web of traditional expectations, jealousy, and fierce ambition ensues when a wealthy patriarch balances multiple households under one roof.	Junior Giti	Drama, Romance	2700	2026	https://www.mediafire.com/file/4fo1bpsic07cdri/Polygamist_%25282026%2529_Ep16.mp4/file	https://image.tmdb.org/t/p/w500/polygamist2026Poster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
The Polygamist Ep 17	A complex web of traditional expectations, jealousy, and fierce ambition ensues when a wealthy patriarch balances multiple households under one roof.	Junior Giti	Drama, Romance	2700	2026	https://www.mediafire.com/file/an6rqtv7qmohi2o/Watch_Polygamist_%25282026%2529_17.mp4/file	https://image.tmdb.org/t/p/w500/polygamist2026Poster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
The Polygamist Ep 18	A complex web of traditional expectations, jealousy, and fierce ambition ensues when a wealthy patriarch balances multiple households under one roof.	Junior Giti	Drama, Romance	2700	2026	https://www.mediafire.com/file/puw7drr2ulp2wn1/Watch_Polygamist_%25282026%2529_18.mp4/file	https://image.tmdb.org/t/p/w500/polygamist2026Poster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
The Polygamist Ep 19	A complex web of traditional expectations, jealousy, and fierce ambition ensues when a wealthy patriarch balances multiple households under one roof.	Junior Giti	Drama, Romance	2700	2026	https://www.mediafire.com/file/qx38v80nrx4gaib/Polygamist_%25282026%2529_19.mp4/file	https://image.tmdb.org/t/p/w500/polygamist2026Poster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
The Polygamist Ep 20	A complex web of traditional expectations, jealousy, and fierce ambition ensues when a wealthy patriarch balances multiple households under one roof.	Junior Giti	Drama, Romance	2700	2026	https://www.mediafire.com/file/9m0n48tqgt2ds7l/Polygamist_%25282026%2529_20.mp4/file	https://image.tmdb.org/t/p/w500/polygamist2026Poster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
The Polygamist Ep 21	A complex web of traditional expectations, jealousy, and fierce ambition ensues when a wealthy patriarch balances multiple households under one roof.	Junior Giti	Drama, Romance	2700	2026	https://www.mediafire.com/file/o3ekggpnf38e8qd/Polygamist_%25282026%2529_21.mp4/file	https://image.tmdb.org/t/p/w500/polygamist2026Poster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
The Polygamist Ep 22 Final	A complex web of traditional expectations, jealousy, and fierce ambition ensues when a wealthy patriarch balances multiple households under one roof.	Junior Giti	Drama, Romance	2700	2026	https://www.mediafire.com/file/rl5hluqnqx9s6x2/Polygamist_%25282026%2529_22_Final_Giti.mp4/file	https://image.tmdb.org/t/p/w500/polygamist2026Poster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com`;

const lines = rawData.trim().split('\n');
const csvLines = lines.map(line => {
  const parts = line.split('\t');
  return parts.map(p => `"${(p || '').trim().replace(/"/g, '""')}"`).join(',');
});

const targetPath = path.join(process.cwd(), 'movies.csv');
fs.appendFileSync(targetPath, '\n' + csvLines.join('\n'));
console.log(`Appended ${csvLines.length} My Country, Six, and Polygamist episodes to movies.csv`);
