import fs from 'fs';
import path from 'path';

const rawData = `One Piece S02 Ep 1	With the Straw Hat Pirates sailing for the Grand Line, Luffy and his crew face ruthless bounty hunters, Marine forces, and treacherous seas in search of the legendary One Piece.	Gaheza Simba	Action, Adventure, Comedy	3300	2026	https://www.mediafire.com/file/k6mdjs52oblxwgn/ONE_PIECE_S2_EP1.mp4/file	https://image.tmdb.org/t/p/w500/fcXdJUSDiDiFupuDuNxBYvdEsTX.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
One Piece S02 Ep 2	With the Straw Hat Pirates sailing for the Grand Line, Luffy and his crew face ruthless bounty hunters, Marine forces, and treacherous seas in search of the legendary One Piece.	Gaheza Simba	Action, Adventure, Comedy	3300	2026	https://www.mediafire.com/file/8prfr6gn4ojah14/ONE_PIECE_S2_EP2.mp4/file	https://image.tmdb.org/t/p/w500/fcXdJUSDiDiFupuDuNxBYvdEsTX.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
One Piece S02 Ep 3	With the Straw Hat Pirates sailing for the Grand Line, Luffy and his crew face ruthless bounty hunters, Marine forces, and treacherous seas in search of the legendary One Piece.	Gaheza Simba	Action, Adventure, Comedy	3300	2026	https://www.mediafire.com/file/w9l5yhqn5h8z2ic/ONE_PIECE_S2_EP3.mp4/file	https://image.tmdb.org/t/p/w500/fcXdJUSDiDiFupuDuNxBYvdEsTX.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
One Piece S02 Ep 4	With the Straw Hat Pirates sailing for the Grand Line, Luffy and his crew face ruthless bounty hunters, Marine forces, and treacherous seas in search of the legendary One Piece.	Gaheza Simba	Action, Adventure, Comedy	3300	2026	https://www.mediafire.com/file/6aeg0egz64dtp6n/ONE_PIECE_S2_EP4.mp4/file	https://image.tmdb.org/t/p/w500/fcXdJUSDiDiFupuDuNxBYvdEsTX.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
One Piece S02 Ep 5	With the Straw Hat Pirates sailing for the Grand Line, Luffy and his crew face ruthless bounty hunters, Marine forces, and treacherous seas in search of the legendary One Piece.	Gaheza Simba	Action, Adventure, Comedy	3300	2026	https://www.mediafire.com/file/6ekmry56ymsqdpe/ONE_PIECE_SE_EP5.mp4/file	https://image.tmdb.org/t/p/w500/fcXdJUSDiDiFupuDuNxBYvdEsTX.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
One Piece S02 Ep 6	With the Straw Hat Pirates sailing for the Grand Line, Luffy and his crew face ruthless bounty hunters, Marine forces, and treacherous seas in search of the legendary One Piece.	Gaheza Simba	Action, Adventure, Comedy	3300	2026	https://www.mediafire.com/file/i4ncseevpe677w3/ONE_PIECE_SE_EP6.mp4/file	https://image.tmdb.org/t/p/w500/fcXdJUSDiDiFupuDuNxBYvdEsTX.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
One Piece S02 Ep 7	With the Straw Hat Pirates sailing for the Grand Line, Luffy and his crew face ruthless bounty hunters, Marine forces, and treacherous seas in search of the legendary One Piece.	Gaheza Simba	Action, Adventure, Comedy	3300	2026	https://www.mediafire.com/file/f53hgpsmmeuurtd/ONE_PIECE_SE_EP7.mp4/file	https://image.tmdb.org/t/p/w500/fcXdJUSDiDiFupuDuNxBYvdEsTX.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
One Piece S02 Ep 8 Final	With the Straw Hat Pirates sailing for the Grand Line, Luffy and his crew face ruthless bounty hunters, Marine forces, and treacherous seas in search of the legendary One Piece.	Gaheza Simba	Action, Adventure, Comedy	3300	2026	https://www.mediafire.com/file/b2d8draimah6ken/One_Piece_S2_Ep8_Final_.mp4/file	https://image.tmdb.org/t/p/w500/fcXdJUSDiDiFupuDuNxBYvdEsTX.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
One Piece S01 Ep 1	In a seafaring world, a young pirate captain sets out with his crew to attain the title of Pirate King, and to discover the mythical treasure known as 'One Piece'.	Gaheza Simba	Action, Adventure, Comedy	3300	2023	https://www.mediafire.com/file/tzw610h7ot2kepp/One_Piece_Ep1.mp4/file	https://image.tmdb.org/t/p/w500/fcXdJUSDiDiFupuDuNxBYvdEsTX.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
One Piece S01 Ep 2 - Part A	In a seafaring world, a young pirate captain sets out with his crew to attain the title of Pirate King, and to discover the mythical treasure known as 'One Piece'.	Gaheza Simba	Action, Adventure, Comedy	3300	2023	https://www.mediafire.com/file/0bjt2xexvzf993h/One_Piece_Ep2a.mp4/file	https://image.tmdb.org/t/p/w500/fcXdJUSDiDiFupuDuNxBYvdEsTX.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
One Piece S01 Ep 2 - Part B	In a seafaring world, a young pirate captain sets out with his crew to attain the title of Pirate King, and to discover the mythical treasure known as 'One Piece'.	Gaheza Simba	Action, Adventure, Comedy	3300	2023	https://www.mediafire.com/file/064gsb4p7082ga9/One_Piece_Ep2b.mp4/file	https://image.tmdb.org/t/p/w500/fcXdJUSDiDiFupuDuNxBYvdEsTX.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
One Piece S01 Ep 3	In a seafaring world, a young pirate captain sets out with his crew to attain the title of Pirate King, and to discover the mythical treasure known as 'One Piece'.	Gaheza Simba	Action, Adventure, Comedy	3300	2023	https://www.mediafire.com/file/d5wjgvgaklcb6x4/One_Piece_Ep3.mp4/file	https://image.tmdb.org/t/p/w500/fcXdJUSDiDiFupuDuNxBYvdEsTX.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
One Piece S01 Ep 4 - Part A	In a seafaring world, a young pirate captain sets out with his crew to attain the title of Pirate King, and to discover the mythical treasure known as 'One Piece'.	Gaheza Simba	Action, Adventure, Comedy	3300	2023	https://www.mediafire.com/file/0ijr4r1x4t5fhpu/One_Piece_Ep4a.mp4/file	https://image.tmdb.org/t/p/w500/fcXdJUSDiDiFupuDuNxBYvdEsTX.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
One Piece S01 Ep 4 - Part B	In a seafaring world, a young pirate captain sets out with his crew to attain the title of Pirate King, and to discover the mythical treasure known as 'One Piece'.	Gaheza Simba	Action, Adventure, Comedy	3300	2023	https://www.mediafire.com/file/b1zzhx5erk4wf0y/One_Piece_Ep4b.mp4/file	https://image.tmdb.org/t/p/w500/fcXdJUSDiDiFupuDuNxBYvdEsTX.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
One Piece S01 Ep 5	In a seafaring world, a young pirate captain sets out with his crew to attain the title of Pirate King, and to discover the mythical treasure known as 'One Piece'.	Gaheza Simba	Action, Adventure, Comedy	3300	2023	https://www.mediafire.com/file/u1mzas4i9fnayw7/One_Piece_Ep5.mp4/file	https://image.tmdb.org/t/p/w500/fcXdJUSDiDiFupuDuNxBYvdEsTX.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
One Piece S01 Ep 6	In a seafaring world, a young pirate captain sets out with his crew to attain the title of Pirate King, and to discover the mythical treasure known as 'One Piece'.	Gaheza Simba	Action, Adventure, Comedy	3300	2023	https://www.mediafire.com/file/emos0os0hi9t1p4/One_Piece_Ep6.mp4/file	https://image.tmdb.org/t/p/w500/fcXdJUSDiDiFupuDuNxBYvdEsTX.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
One Piece S01 Ep 7	In a seafaring world, a young pirate captain sets out with his crew to attain the title of Pirate King, and to discover the mythical treasure known as 'One Piece'.	Gaheza Simba	Action, Adventure, Comedy	3300	2023	https://www.mediafire.com/file/hla59ssdxf93hg7/One_Piece_Ep7.mp4/file	https://image.tmdb.org/t/p/w500/fcXdJUSDiDiFupuDuNxBYvdEsTX.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
One Piece S01 Ep 8 Final	In a seafaring world, a young pirate captain sets out with his crew to attain the title of Pirate King, and to discover the mythical treasure known as 'One Piece'.	Gaheza Simba	Action, Adventure, Comedy	3300	2023	https://www.mediafire.com/file/zjtfk4t9pfyqprk/One_Piece_Ep8_Final.mp4/file	https://image.tmdb.org/t/p/w500/fcXdJUSDiDiFupuDuNxBYvdEsTX.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Vikings: Valhalla S03 Ep 1	Set over a thousand years ago, this sequel chronicles the heroic adventures of some of the most famous Vikings who ever lived, exploring new territories from Constantinople to Greenland.	Gaheza Simba	Action, Adventure, Drama	2820	2024	https://www.mediafire.com/file/qw0otr9q9urq63h/VIKINGS_VALHALLA_S3E01.mp4/file	https://image.tmdb.org/t/p/w500/vikingsValhallaS3Poster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Vikings: Valhalla S03 Ep 2	Set over a thousand years ago, this sequel chronicles the heroic adventures of some of the most famous Vikings who ever lived, exploring new territories from Constantinople to Greenland.	Gaheza Simba	Action, Adventure, Drama	2820	2024	https://www.mediafire.com/file/kl33egpy3ikdxh5/VIKINGS_VALHALLA_S3E02.mp4/file	https://image.tmdb.org/t/p/w500/vikingsValhallaS3Poster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Vikings: Valhalla S03 Ep 3	Set over a thousand years ago, this sequel chronicles the heroic adventures of some of the most famous Vikings who ever lived, exploring new territories from Constantinople to Greenland.	Gaheza Simba	Action, Adventure, Drama	2820	2024	https://www.mediafire.com/file/y7mytjyi1ar9423/VIKING_VALHALLA_S03E03.mp4/file	https://image.tmdb.org/t/p/w500/vikingsValhallaS3Poster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Vikings: Valhalla S03 Ep 4	Set over a thousand years ago, this sequel chronicles the heroic adventures of some of the most famous Vikings who ever lived, exploring new territories from Constantinople to Greenland.	Gaheza Simba	Action, Adventure, Drama	2820	2024	https://www.mediafire.com/file/a1ft0oswgd00bjh/VIKINGS_VALHALLA_S3E04.mp4/file	https://image.tmdb.org/t/p/w500/vikingsValhallaS3Poster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Vikings: Valhalla S03 Ep 5	Set over a thousand years ago, this sequel chronicles the heroic adventures of some of the most famous Vikings who ever lived, exploring new territories from Constantinople to Greenland.	Gaheza Simba	Action, Adventure, Drama	2820	2024	https://www.mediafire.com/file/dt3adee1hh4sn1a/VIKINGS_VALHALLA_S3E5.mp4/file	https://image.tmdb.org/t/p/w500/vikingsValhallaS3Poster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Vikings: Valhalla S03 Ep 6	Set over a thousand years ago, this sequel chronicles the heroic adventures of some of the most famous Vikings who ever lived, exploring new territories from Constantinople to Greenland.	Gaheza Simba	Action, Adventure, Drama	2820	2024	https://www.mediafire.com/file/u6751xg09zxxq0t/VIKINGS_VALHALLA_S3E6.mp4/file	https://image.tmdb.org/t/p/w500/vikingsValhallaS3Poster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Vikings: Valhalla S03 Ep 7	Set over a thousand years ago, this sequel chronicles the heroic adventures of some of the most famous Vikings who ever lived, exploring new territories from Constantinople to Greenland.	Gaheza Simba	Action, Adventure, Drama	2820	2024	https://www.mediafire.com/file/vodcgjfdpm01urj/VIKINGS_VALHALLA_S3E7.mp4/file	https://image.tmdb.org/t/p/w500/vikingsValhallaS3Poster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Vikings: Valhalla S03 Ep 8 Final	Set over a thousand years ago, this sequel chronicles the heroic adventures of some of the most famous Vikings who ever lived, exploring new territories from Constantinople to Greenland.	Gaheza Simba	Action, Adventure, Drama	2820	2024	https://www.mediafire.com/file/om921f2oi4h02lo/VIKINGS_VALHALLA_S3_EP8_FINAL.mp4/file	https://image.tmdb.org/t/p/w500/vikingsValhallaS3Poster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Vikings: Valhalla S02 Ep 1	Enemies old and new await Freydis, Leif, and Harald as they scatter to the far corners of the globe in pursuit of power and new worlds to conquer.	Gaheza Simba	Action, Adventure, Drama	2820	2023	https://www.mediafire.com/file/1g7g8qkz4omychn/Vikings_Valhalla_S2_Ep1.mp4/file	https://image.tmdb.org/t/p/w500/vikingsValhallaS2Poster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Vikings: Valhalla S02 Ep 2	Enemies old and new await Freydis, Leif, and Harald as they scatter to the far corners of the globe in pursuit of power and new worlds to conquer.	Gaheza Simba	Action, Adventure, Drama	2820	2023	https://www.mediafire.com/file/rwhc7o65zmwwlub/Vikings_Valhalla_S2_Ep2.mp4/file	https://image.tmdb.org/t/p/w500/vikingsValhallaS2Poster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Vikings: Valhalla S02 Ep 3	Enemies old and new await Freydis, Leif, and Harald as they scatter to the far corners of the globe in pursuit of power and new worlds to conquer.	Gaheza Simba	Action, Adventure, Drama	2820	2023	https://www.mediafire.com/file/uwautw6sq3cw8v8/Vikings_Valhalla_S2_Ep3.mp4/file	https://image.tmdb.org/t/p/w500/vikingsValhallaS2Poster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Vikings: Valhalla S02 Ep 4	Enemies old and new await Freydis, Leif, and Harald as they scatter to the far corners of the globe in pursuit of power and new worlds to conquer.	Gaheza Simba	Action, Adventure, Drama	2820	2023	https://www.mediafire.com/file/afc5gyhxizai3x4/Vikings_Valhalla_S2_Ep4.mp4/file	https://image.tmdb.org/t/p/w500/vikingsValhallaS2Poster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Vikings: Valhalla S02 Ep 5	Enemies old and new await Freydis, Leif, and Harald as they scatter to the far corners of the globe in pursuit of power and new worlds to conquer.	Gaheza Simba	Action, Adventure, Drama	2820	2023	https://www.mediafire.com/file/9lqoiphz84wj48m/Vikings_Valhalla_S2_Ep5.mp4/file	https://image.tmdb.org/t/p/w500/vikingsValhallaS2Poster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Vikings: Valhalla S02 Ep 6	Enemies old and new await Freydis, Leif, and Harald as they scatter to the far corners of the globe in pursuit of power and new worlds to conquer.	Gaheza Simba	Action, Adventure, Drama	2820	2023	https://www.mediafire.com/file/0zi81c1qybwsx0w/Vikings_Valhalla_S2_Ep6.mp4/file	https://image.tmdb.org/t/p/w500/vikingsValhallaS2Poster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Vikings: Valhalla S02 Ep 7 - Part A	Enemies old and new await Freydis, Leif, and Harald as they scatter to the far corners of the globe in pursuit of power and new worlds to conquer.	Gaheza Simba	Action, Adventure, Drama	2820	2023	https://www.mediafire.com/file/vk999rqe2wd2gw2/Vikings_Valhalla_S2_Ep7a.mp4/file	https://image.tmdb.org/t/p/w500/vikingsValhallaS2Poster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Vikings: Valhalla S02 Ep 8 Final	Enemies old and new await Freydis, Leif, and Harald as they scatter to the far corners of the globe in pursuit of power and new worlds to conquer.	Gaheza Simba	Action, Adventure, Drama	2820	2023	https://www.mediafire.com/file/sh4vsdmhm7391bf/Vikings_Valhalla_S2_Ep8_Final.mp4/file	https://image.tmdb.org/t/p/w500/vikingsValhallaS2Poster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com`;

const lines = rawData.trim().split('\n');
const csvLines = lines.map(line => {
  const parts = line.split('\t');
  return parts.map(p => `"${(p || '').trim().replace(/"/g, '""')}"`).join(',');
});

const targetPath = path.join(process.cwd(), 'movies.csv');
fs.appendFileSync(targetPath, '\n' + csvLines.join('\n'));
console.log(`Appended ${csvLines.length} One Piece and Vikings episodes to movies.csv`);
