import fs from 'fs';
import path from 'path';

const rawData = `Prison Break S05 Ep 1	When clues surface that suggest a previously thought-to-be-dead Michael Scofield may be alive in a Yemeni prison, Lincoln and Sara reunite to engineer his escape.	Junior Giti	Action, Crime, Drama, Thriller	2640	2017	https://www.mediafire.com/file/v317shga35kxfcu/Prison_Break_S05_E1_Mp4.mp4/file	https://image.tmdb.org/t/p/w500/prisonBreakS5Poster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Prison Break S05 Ep 2	When clues surface that suggest a previously thought-to-be-dead Michael Scofield may be alive in a Yemeni prison, Lincoln and Sara reunite to engineer his escape.	Junior Giti	Action, Crime, Drama, Thriller	2640	2017	https://www.mediafire.com/file/oaq64uheysy4ivo/Prison_Break_S05_Ep2_Mp4.mp4/file	https://image.tmdb.org/t/p/w500/prisonBreakS5Poster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Prison Break S05 Ep 3	When clues surface that suggest a previously thought-to-be-dead Michael Scofield may be alive in a Yemeni prison, Lincoln and Sara reunite to engineer his escape.	Junior Giti	Action, Crime, Drama, Thriller	2640	2017	https://www.mediafire.com/file/kz4in7ocpfbf4ek/Prison_Break_S05_Ep3_Mp4.mp4/file	https://image.tmdb.org/t/p/w500/prisonBreakS5Poster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Prison Break S05 Ep 4	When clues surface that suggest a previously thought-to-be-dead Michael Scofield may be alive in a Yemeni prison, Lincoln and Sara reunite to engineer his escape.	Junior Giti	Action, Crime, Drama, Thriller	2640	2017	https://www.mediafire.com/file/1uacybjvwcc0bb5/Prison_Break_S05_Ep4_Mp4.mp4/file	https://image.tmdb.org/t/p/w500/prisonBreakS5Poster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Prison Break S05 Ep 5	When clues surface that suggest a previously thought-to-be-dead Michael Scofield may be alive in a Yemeni prison, Lincoln and Sara reunite to engineer his escape.	Junior Giti	Action, Crime, Drama, Thriller	2640	2017	https://www.mediafire.com/file/du5ipr0rf4jinxs/Prison_Break_S05_Ep5_Mp4.mp4/file	https://image.tmdb.org/t/p/w500/prisonBreakS5Poster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Prison Break S05 Ep 6	When clues surface that suggest a previously thought-to-be-dead Michael Scofield may be alive in a Yemeni prison, Lincoln and Sara reunite to engineer his escape.	Junior Giti	Action, Crime, Drama, Thriller	2640	2017	https://www.mediafire.com/file/wxmd89l6v05lxf3/Prison_Break_S05_Ep6_Mp4.mp4/file	https://image.tmdb.org/t/p/w500/prisonBreakS5Poster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Prison Break S05 Ep 7	When clues surface that suggest a previously thought-to-be-dead Michael Scofield may be alive in a Yemeni prison, Lincoln and Sara reunite to engineer his escape.	Junior Giti	Action, Crime, Drama, Thriller	2640	2017	https://www.mediafire.com/file/n597z2gzx4j9cvf/Prison_Break_S05_Ep7_Mp4.mp4/file	https://image.tmdb.org/t/p/w500/prisonBreakS5Poster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Prison Break S05 Ep 8	When clues surface that suggest a previously thought-to-be-dead Michael Scofield may be alive in a Yemeni prison, Lincoln and Sara reunite to engineer his escape.	Junior Giti	Action, Crime, Drama, Thriller	2640	2017	https://www.mediafire.com/file/siq24rlkm26w1ek/Prison_Break_S05_Ep8_Mp4.mp4/file	https://image.tmdb.org/t/p/w500/prisonBreakS5Poster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Prison Break S05 Ep 9 Final	When clues surface that suggest a previously thought-to-be-dead Michael Scofield may be alive in a Yemeni prison, Lincoln and Sara reunite to engineer his escape.	Junior Giti	Action, Crime, Drama, Thriller	2640	2017	https://www.mediafire.com/file/zjxsxpqhiaxumtg/Prison_Break_S05_Ep9_Final_Mp4.mp4/file	https://image.tmdb.org/t/p/w500/prisonBreakS5Poster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Prison Break S04 Ep 01	Michael Scofield and his crew seek retribution against The Company, a shadowy syndicate that framed him and ruined the lives of his family and friends.	Junior Giti	Action, Crime, Drama, Thriller	2640	2008	https://www.mediafire.com/file/7xv2wddv7o6jj4q/Prison_Break_S04_Ep1_Mp4.mp4/file	https://image.tmdb.org/t/p/w500/prisonBreakS4Poster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Prison Break S04 Ep 02	Michael Scofield and his crew seek retribution against The Company, a shadowy syndicate that framed him and ruined the lives of his family and friends.	Junior Giti	Action, Crime, Drama, Thriller	2640	2008	https://www.mediafire.com/file/6jpls1sa9r6gdgy/Prison_Break_S04_Ep2_Mp4.mp4/file	https://image.tmdb.org/t/p/w500/prisonBreakS4Poster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Prison Break S04 Ep 03	Michael Scofield and his crew seek retribution against The Company, a shadowy syndicate that framed him and ruined the lives of his family and friends.	Junior Giti	Action, Crime, Drama, Thriller	2640	2008	https://www.mediafire.com/file/2xo51htchj6jak2/Prison_Break_S04_Ep3_Mp4.mp4/file	https://image.tmdb.org/t/p/w500/prisonBreakS4Poster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Prison Break S04 Ep 04	Michael Scofield and his crew seek retribution against The Company, a shadowy syndicate that framed him and ruined the lives of his family and friends.	Junior Giti	Action, Crime, Drama, Thriller	2640	2008	https://www.mediafire.com/file/ajfx7mzxfojxqqw/Prison_Break_S04_Ep4_Mp4.mp4/file	https://image.tmdb.org/t/p/w500/prisonBreakS4Poster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Prison Break S04 Ep 05	Michael Scofield and his crew seek retribution against The Company, a shadowy syndicate that framed him and ruined the lives of his family and friends.	Junior Giti	Action, Crime, Drama, Thriller	2640	2008	https://www.mediafire.com/file/gulgcx7blcmusvp/Prison_Break_S04_Ep5_Mp4.mp4/file	https://image.tmdb.org/t/p/w500/prisonBreakS4Poster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Prison Break S04 Ep 06	Michael Scofield and his crew seek retribution against The Company, a shadowy syndicate that framed him and ruined the lives of his family and friends.	Junior Giti	Action, Crime, Drama, Thriller	2640	2008	https://www.mediafire.com/file/ukc5ahvx4bw88ii/Prison__Break_S04_Ep6_Mp4.mp4/file	https://image.tmdb.org/t/p/w500/prisonBreakS4Poster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Prison Break S04 Ep 07	Michael Scofield and his crew seek retribution against The Company, a shadowy syndicate that framed him and ruined the lives of his family and friends.	Junior Giti	Action, Crime, Drama, Thriller	2640	2008	https://www.mediafire.com/file/yjv1zqxfwvjjh7s/Prison_Break_S04_E7_Mp4.mp4/file	https://image.tmdb.org/t/p/w500/prisonBreakS4Poster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Prison Break S04 Ep 08	Michael Scofield and his crew seek retribution against The Company, a shadowy syndicate that framed him and ruined the lives of his family and friends.	Junior Giti	Action, Crime, Drama, Thriller	2640	2008	https://www.mediafire.com/file/q3ypjajictlav2l/Prison_Break_S04_E8_Mp4.mp4/file	https://image.tmdb.org/t/p/w500/prisonBreakS4Poster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Prison Break S04 Ep 09	Michael Scofield and his crew seek retribution against The Company, a shadowy syndicate that framed him and ruined the lives of his family and friends.	Junior Giti	Action, Crime, Drama, Thriller	2640	2008	https://www.mediafire.com/file/we4zzcms1izgtqr/Prison_Break_S04_Ep9_Mp4.mp4/file	https://image.tmdb.org/t/p/w500/prisonBreakS4Poster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Prison Break S04 Ep 10	Michael Scofield and his crew seek retribution against The Company, a shadowy syndicate that framed him and ruined the lives of his family and friends.	Junior Giti	Action, Crime, Drama, Thriller	2640	2008	https://www.mediafire.com/file/yro3k0w4fmmjg79/Prison_Break_S04_Ep10_Mp4.mp4/file	https://image.tmdb.org/t/p/w500/prisonBreakS4Poster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Prison Break S04 Ep 11	Michael Scofield and his crew seek retribution against The Company, a shadowy syndicate that framed him and ruined the lives of his family and friends.	Junior Giti	Action, Crime, Drama, Thriller	2640	2008	https://www.mediafire.com/file/moufok1r3tfxvxn/Prison_Break_S04_Ep11_Mp4.mp4/file	https://image.tmdb.org/t/p/w500/prisonBreakS4Poster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Prison Break S04 Ep 12	Michael Scofield and his crew seek retribution against The Company, a shadowy syndicate that framed him and ruined the lives of his family and friends.	Junior Giti	Action, Crime, Drama, Thriller	2640	2008	https://www.mediafire.com/file/o64qj96f6vb95nj/Prison_Break_S04_Ep12_Mp4.mp4/file	https://image.tmdb.org/t/p/w500/prisonBreakS4Poster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Prison Break S04 Ep 13	Michael Scofield and his crew seek retribution against The Company, a shadowy syndicate that framed him and ruined the lives of his family and friends.	Junior Giti	Action, Crime, Drama, Thriller	2640	2008	https://www.mediafire.com/file/9ymj6aoe6ltytiz/Prison_Break_S04_Ep13_Mp4.mp4/file	https://image.tmdb.org/t/p/w500/prisonBreakS4Poster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Prison Break S04 Ep 14	Michael Scofield and his crew seek retribution against The Company, a shadowy syndicate that framed him and ruined the lives of his family and friends.	Junior Giti	Action, Crime, Drama, Thriller	2640	2008	https://www.mediafire.com/file/g2n913kvacvxvcd/Prison_Break_S04_Ep14_Mp4.mp4/file	https://image.tmdb.org/t/p/w500/prisonBreakS4Poster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Prison Break S04 Ep 15	Michael Scofield and his crew seek retribution against The Company, a shadowy syndicate that framed him and ruined the lives of his family and friends.	Junior Giti	Action, Crime, Drama, Thriller	2640	2008	https://www.mediafire.com/file/opiz8dt1m2mvdj6/Prison_Break_S04_Ep15_Mp4.mp4/file	https://image.tmdb.org/t/p/w500/prisonBreakS4Poster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Prison Break S04 Ep 16	Michael Scofield and his crew seek retribution against The Company, a shadowy syndicate that framed him and ruined the lives of his family and friends.	Junior Giti	Action, Crime, Drama, Thriller	2640	2008	https://www.mediafire.com/file/pa6q6ywoni8gksm/Prison_Break_S04_Ep16_Mp4.mp4/file	https://image.tmdb.org/t/p/w500/prisonBreakS4Poster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Prison Break S04 Ep 17	Michael Scofield and his crew seek retribution against The Company, a shadowy syndicate that framed him and ruined the lives of his family and friends.	Junior Giti	Action, Crime, Drama, Thriller	2640	2008	https://www.mediafire.com/file/fhfa6234ia1z4zy/Prison_Berak_S04_Ep17_Mp4.mp4/file	https://image.tmdb.org/t/p/w500/prisonBreakS4Poster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Prison Break S04 Ep 18	Michael Scofield and his crew seek retribution against The Company, a shadowy syndicate that framed him and ruined the lives of his family and friends.	Junior Giti	Action, Crime, Drama, Thriller	2640	2008	https://www.mediafire.com/file/upuacjrg4kikvkg/Prison_Break_S04_Ep18_Mp4.mp4/file	https://image.tmdb.org/t/p/w500/prisonBreakS4Poster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Prison Break S04 Ep 19	Michael Scofield and his crew seek retribution against The Company, a shadowy syndicate that framed him and ruined the lives of his family and friends.	Junior Giti	Action, Crime, Drama, Thriller	2640	2008	https://www.mediafire.com/file/5rxho9f19lle91e/Prison_Break_S04_Ep19_Mp4.mp4/file	https://image.tmdb.org/t/p/w500/prisonBreakS4Poster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Prison Break S04 Ep 20	Michael Scofield and his crew seek retribution against The Company, a shadowy syndicate that framed him and ruined the lives of his family and friends.	Junior Giti	Action, Crime, Drama, Thriller	2640	2008	https://www.mediafire.com/file/27xh6t7ag86gixv/Prison_Break_S04_Ep20_Mp4.mp4/file	https://image.tmdb.org/t/p/w500/prisonBreakS4Poster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Prison Break S04 Ep 21	Michael Scofield and his crew seek retribution against The Company, a shadowy syndicate that framed him and ruined the lives of his family and friends.	Junior Giti	Action, Crime, Drama, Thriller	2640	2008	https://www.mediafire.com/file/k3lehj56cv4cc3q/Prison_Break_S04_Ep21.mp4/file	https://image.tmdb.org/t/p/w500/prisonBreakS4Poster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Prison Break S04 Ep 22 Final	Michael Scofield and his crew seek retribution against The Company, a shadowy syndicate that framed him and ruined the lives of his family and friends.	Junior Giti	Action, Crime, Drama, Thriller	2640	2008	https://www.mediafire.com/file/pac36kfw3u0b5ul/Prison_B_Reak_S04_Final_Mp4.mp4/file	https://image.tmdb.org/t/p/w500/prisonBreakS4Poster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Prison Break S03 Ep 01	Michael Scofield finds himself incarcerated in Sona, a deadly Panamanian prison where riots have driven out the guards, and is tasked with breaking out another inmate.	Junior Giti	Action, Crime, Drama, Thriller	2640	2007	https://www.mediafire.com/file/xnbfj9cofcna058/Prison_Break_S03_Ep1_Mp4.mp4/file	https://image.tmdb.org/t/p/w500/prisonBreakS3Poster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Prison Break S03 Ep 02	Michael Scofield finds himself incarcerated in Sona, a deadly Panamanian prison where riots have driven out the guards, and is tasked with breaking out another inmate.	Junior Giti	Action, Crime, Drama, Thriller	2640	2007	https://www.mediafire.com/file/27fbka6ntvzvbjs/Prison_Break_S03_Ep2_Mp4.mp4/file	https://image.tmdb.org/t/p/w500/prisonBreakS3Poster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Prison Break S03 Ep 03	Michael Scofield finds himself incarcerated in Sona, a deadly Panamanian prison where riots have driven out the guards, and is tasked with breaking out another inmate.	Junior Giti	Action, Crime, Drama, Thriller	2640	2007	https://www.mediafire.com/file/i4pj1ko3qsijpbp/Prison_Break_S03_Ep3_Mp4.mp4/file	https://image.tmdb.org/t/p/w500/prisonBreakS3Poster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Prison Break S03 Ep 04	Michael Scofield finds himself incarcerated in Sona, a deadly Panamanian prison where riots have driven out the guards, and is tasked with breaking out another inmate.	Junior Giti	Action, Crime, Drama, Thriller	2640	2007	https://www.mediafire.com/file/qmny47zf9isoc7w/Prison_Break_S03_Ep4_Mp4.mp4/file	https://image.tmdb.org/t/p/w500/prisonBreakS3Poster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Prison Break S03 Ep 05	Michael Scofield finds himself incarcerated in Sona, a deadly Panamanian prison where riots have driven out the guards, and is tasked with breaking out another inmate.	Junior Giti	Action, Crime, Drama, Thriller	2640	2007	https://www.mediafire.com/file/zn582x5anlfg8su/Prison_Break_S03_Ep5_Mp4.mp4/file	https://image.tmdb.org/t/p/w500/prisonBreakS3Poster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Prison Break S03 Ep 06	Michael Scofield finds himself incarcerated in Sona, a deadly Panamanian prison where riots have driven out the guards, and is tasked with breaking out another inmate.	Junior Giti	Action, Crime, Drama, Thriller	2640	2007	https://www.mediafire.com/file/q061rzx5z0ufy5x/Prison_Break_S03_Ep6_Mp4.mp4/file	https://image.tmdb.org/t/p/w500/prisonBreakS3Poster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Prison Break S03 Ep 07	Michael Scofield finds himself incarcerated in Sona, a deadly Panamanian prison where riots have driven out the guards, and is tasked with breaking out another inmate.	Junior Giti	Action, Crime, Drama, Thriller	2640	2007	https://www.mediafire.com/file/kzqpj9v7w3yjeha/Prison_Break_S03_Ep7_Mp4.mp4/file	https://image.tmdb.org/t/p/w500/prisonBreakS3Poster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Prison Break S03 Ep 08	Michael Scofield finds himself incarcerated in Sona, a deadly Panamanian prison where riots have driven out the guards, and is tasked with breaking out another inmate.	Junior Giti	Action, Crime, Drama, Thriller	2640	2007	https://www.mediafire.com/file/i4w9he9wt4h1peb/Prisom_Break_S03_Ep8_Mp4.mp4/file	https://image.tmdb.org/t/p/w500/prisonBreakS3Poster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Prison Break S03 Ep 09	Michael Scofield finds himself incarcerated in Sona, a deadly Panamanian prison where riots have driven out the guards, and is tasked with breaking out another inmate.	Junior Giti	Action, Crime, Drama, Thriller	2640	2007	https://www.mediafire.com/file/x6y41zlfzv9gnb4/Prison_Break_S3_Ep9.mp4/file	https://image.tmdb.org/t/p/w500/prisonBreakS3Poster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Prison Break S03 Ep 10	Michael Scofield finds himself incarcerated in Sona, a deadly Panamanian prison where riots have driven out the guards, and is tasked with breaking out another inmate.	Junior Giti	Action, Crime, Drama, Thriller	2640	2007	https://www.mediafire.com/file/7a191htnx9pivc6/Prison_Break_S03_Ep10_Mp4.mp4/file	https://image.tmdb.org/t/p/w500/prisonBreakS3Poster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Prison Break S03 Ep 11	Michael Scofield finds himself incarcerated in Sona, a deadly Panamanian prison where riots have driven out the guards, and is tasked with breaking out another inmate.	Junior Giti	Action, Crime, Drama, Thriller	2640	2007	https://www.mediafire.com/file/id1lhh79c4vo2r7/Prison_Break_S03_Ep11_Mp4.mp4/file	https://image.tmdb.org/t/p/w500/prisonBreakS3Poster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Prison Break S03 Ep 12	Michael Scofield finds himself incarcerated in Sona, a deadly Panamanian prison where riots have driven out the guards, and is tasked with breaking out another inmate.	Junior Giti	Action, Crime, Drama, Thriller	2640	2007	https://www.mediafire.com/file/gr771erqgt70004/Prison_Break_S03_Ep12_Mp4.mp4/file	https://image.tmdb.org/t/p/w500/prisonBreakS3Poster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Prison Break S03 Ep 13 Final	Michael Scofield finds himself incarcerated in Sona, a deadly Panamanian prison where riots have driven out the guards, and is tasked with breaking out another inmate.	Junior Giti	Action, Crime, Drama, Thriller	2640	2007	https://www.mediafire.com/file/ywnylav9p9kzmj2/Prison_Break_S03_Ep13_Final_Mp4.mp4/file	https://image.tmdb.org/t/p/w500/prisonBreakS3Poster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Prison Break S02 Ep 01	Now fugitives on the run across the country, the Fox River Eight race to find buried millions while being relentlessly pursued by FBI agent Alexander Mahone.	Junior Giti	Action, Crime, Drama, Thriller	2640	2006	https://www.mediafire.com/file/cw3ddhjc9r81o6p/Prison_Break_S02_Ep1_Mp4.mp4/file	https://image.tmdb.org/t/p/w500/prisonBreakS2Poster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Prison Break S02 Ep 02	Now fugitives on the run across the country, the Fox River Eight race to find buried millions while being relentlessly pursued by FBI agent Alexander Mahone.	Junior Giti	Action, Crime, Drama, Thriller	2640	2006	https://www.mediafire.com/file/4y0lmrmkiq1wsoq/Prison_Break_S02_Ep2_Mp4.mp4/file	https://image.tmdb.org/t/p/w500/prisonBreakS2Poster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Prison Break S02 Ep 03	Now fugitives on the run across the country, the Fox River Eight race to find buried millions while being relentlessly pursued by FBI agent Alexander Mahone.	Junior Giti	Action, Crime, Drama, Thriller	2640	2006	https://www.mediafire.com/file/gq3ucijlao1poji/Prison_Break_S02_Ep3_Mp4.mp4/file	https://image.tmdb.org/t/p/w500/prisonBreakS2Poster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Prison Break S02 Ep 04	Now fugitives on the run across the country, the Fox River Eight race to find buried millions while being relentlessly pursued by FBI agent Alexander Mahone.	Junior Giti	Action, Crime, Drama, Thriller	2640	2006	https://www.mediafire.com/file/4zu9edo0njb4ihz/Prison_Break_S02_Ep4_Mp4.mp4/file	https://image.tmdb.org/t/p/w500/prisonBreakS2Poster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Prison Break S02 Ep 05	Now fugitives on the run across the country, the Fox River Eight race to find buried millions while being relentlessly pursued by FBI agent Alexander Mahone.	Junior Giti	Action, Crime, Drama, Thriller	2640	2006	https://www.mediafire.com/file/0ljpwhlgcz2vrvj/Prison_Break_S02_Ep5_Mp4.mp4/file	https://image.tmdb.org/t/p/w500/prisonBreakS2Poster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Prison Break S02 Ep 06	Now fugitives on the run across the country, the Fox River Eight race to find buried millions while being relentlessly pursued by FBI agent Alexander Mahone.	Junior Giti	Action, Crime, Drama, Thriller	2640	2006	https://www.mediafire.com/file/ww8kids56iczkqo/Prison_Break_S02_Ep6_Mp4%25281%2529.mp4/file	https://image.tmdb.org/t/p/w500/prisonBreakS2Poster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Prison Break S02 Ep 07	Now fugitives on the run across the country, the Fox River Eight race to find buried millions while being relentlessly pursued by FBI agent Alexander Mahone.	Junior Giti	Action, Crime, Drama, Thriller	2640	2006	https://www.mediafire.com/file/44hrej2kogrsr44/Prison_Break_S02_Ep7_Mp4%25281%2529.mp4/file	https://image.tmdb.org/t/p/w500/prisonBreakS2Poster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Prison Break S02 Ep 08	Now fugitives on the run across the country, the Fox River Eight race to find buried millions while being relentlessly pursued by FBI agent Alexander Mahone.	Junior Giti	Action, Crime, Drama, Thriller	2640	2006	https://www.mediafire.com/file/xje8cjxgbrn5pq8/Prison_Break_S02_Ep8_Mp4%25281%2529.mp4/file	https://image.tmdb.org/t/p/w500/prisonBreakS2Poster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Prison Break S02 Ep 09	Now fugitives on the run across the country, the Fox River Eight race to find buried millions while being relentlessly pursued by FBI agent Alexander Mahone.	Junior Giti	Action, Crime, Drama, Thriller	2640	2006	https://www.mediafire.com/file/l6d95dx4absm7jv/Prison_Break_S02_Ep9_Mp4%25281%2529.mp4/file	https://image.tmdb.org/t/p/w500/prisonBreakS2Poster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Prison Break S02 Ep 10	Now fugitives on the run across the country, the Fox River Eight race to find buried millions while being relentlessly pursued by FBI agent Alexander Mahone.	Junior Giti	Action, Crime, Drama, Thriller	2640	2006	https://www.mediafire.com/file/sdn5zo878arwmta/Prison_Break_S02_Ep10_Mp4%25281%2529.mp4/file	https://image.tmdb.org/t/p/w500/prisonBreakS2Poster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Prison Break S02 Ep 11	Now fugitives on the run across the country, the Fox River Eight race to find buried millions while being relentlessly pursued by FBI agent Alexander Mahone.	Junior Giti	Action, Crime, Drama, Thriller	2640	2006	https://www.mediafire.com/file/6e9hfrq8t022dex/Prison_Break_S02_Ep11_Mp4.mp4/file	https://image.tmdb.org/t/p/w500/prisonBreakS2Poster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Prison Break S02 Ep 12	Now fugitives on the run across the country, the Fox River Eight race to find buried millions while being relentlessly pursued by FBI agent Alexander Mahone.	Junior Giti	Action, Crime, Drama, Thriller	2640	2006	https://www.mediafire.com/file/b8fpyogo4s0uzou/Prison_Break_S02_Ep12_Mp4.mp4/file	https://image.tmdb.org/t/p/w500/prisonBreakS2Poster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Prison Break S02 Ep 13	Now fugitives on the run across the country, the Fox River Eight race to find buried millions while being relentlessly pursued by FBI agent Alexander Mahone.	Junior Giti	Action, Crime, Drama, Thriller	2640	2006	https://www.mediafire.com/file/c10nuhi0pzjoe0k/Prison_Break_S02_Ep13_Mp4.mp4/file	https://image.tmdb.org/t/p/w500/prisonBreakS2Poster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Prison Break S02 Ep 14	Now fugitives on the run across the country, the Fox River Eight race to find buried millions while being relentlessly pursued by FBI agent Alexander Mahone.	Junior Giti	Action, Crime, Drama, Thriller	2640	2006	https://www.mediafire.com/file/e7vbo5tnp8pyhaw/Prison_Break_S02_Ep14_Mp4.mp4/file	https://image.tmdb.org/t/p/w500/prisonBreakS2Poster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Prison Break S02 Ep 15	Now fugitives on the run across the country, the Fox River Eight race to find buried millions while being relentlessly pursued by FBI agent Alexander Mahone.	Junior Giti	Action, Crime, Drama, Thriller	2640	2006	https://www.mediafire.com/file/gpztzc67u0bxt4n/Prison_Break_S02_Ep15_Mp4.mp4/file	https://image.tmdb.org/t/p/w500/prisonBreakS2Poster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Prison Break S02 Ep 16	Now fugitives on the run across the country, the Fox River Eight race to find buried millions while being relentlessly pursued by FBI agent Alexander Mahone.	Junior Giti	Action, Crime, Drama, Thriller	2640	2006	https://www.mediafire.com/file/1ob9lnuxaocbj7w/Prion_Break_S02_Ep16_Mp4.mp4/file	https://image.tmdb.org/t/p/w500/prisonBreakS2Poster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Prison Break S02 Ep 17	Now fugitives on the run across the country, the Fox River Eight race to find buried millions while being relentlessly pursued by FBI agent Alexander Mahone.	Junior Giti	Action, Crime, Drama, Thriller	2640	2006	https://www.mediafire.com/file/9l7a7s9en6bh62b/Prison_Break_S02_Ep17_Mp4.mp4/file	https://image.tmdb.org/t/p/w500/prisonBreakS2Poster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Prison Break S02 Ep 18	Now fugitives on the run across the country, the Fox River Eight race to find buried millions while being relentlessly pursued by FBI agent Alexander Mahone.	Junior Giti	Action, Crime, Drama, Thriller	2640	2006	https://www.mediafire.com/file/hplo1hjphqr7puw/Prison_Break_S02_Ep18_Mp4.mp4/file	https://image.tmdb.org/t/p/w500/prisonBreakS2Poster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Prison Break S02 Ep 19	Now fugitives on the run across the country, the Fox River Eight race to find buried millions while being relentlessly pursued by FBI agent Alexander Mahone.	Junior Giti	Action, Crime, Drama, Thriller	2640	2006	https://www.mediafire.com/file/94iw8dvx542u856/Prison_Break_S02_Ep19_Mp4.mp4/file	https://image.tmdb.org/t/p/w500/prisonBreakS2Poster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Prison Break S02 Ep 20	Now fugitives on the run across the country, the Fox River Eight race to find buried millions while being relentlessly pursued by FBI agent Alexander Mahone.	Junior Giti	Action, Crime, Drama, Thriller	2640	2006	https://www.mediafire.com/file/e6h8f0pz8enwlij/Prison_Break_S02_Ep20_Mp4.mp4/file	https://image.tmdb.org/t/p/w500/prisonBreakS2Poster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Prison Break S02 Ep 21	Now fugitives on the run across the country, the Fox River Eight race to find buried millions while being relentlessly pursued by FBI agent Alexander Mahone.	Junior Giti	Action, Crime, Drama, Thriller	2640	2006	https://www.mediafire.com/file/zsarmci36vqy0q4/Prison_Break_S02_Ep21_Mp4.mp4/file	https://image.tmdb.org/t/p/w500/prisonBreakS2Poster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Prison Break S02 Ep 22 Final	Now fugitives on the run across the country, the Fox River Eight race to find buried millions while being relentlessly pursued by FBI agent Alexander Mahone.	Junior Giti	Action, Crime, Drama, Thriller	2640	2006	https://www.mediafire.com/file/au3svkk8e9uqg0b/Prison_Break_S02_Ep22_Final_Mp4.mp4/file	https://image.tmdb.org/t/p/w500/prisonBreakS2Poster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Prison Break S01 Ep 01	An engineer installs himself in a prison he helped design, in order to save his falsely accused brother from a death sentence.	Junior Giti	Action, Crime, Drama, Thriller	2640	2005	https://www.mediafire.com/file/1c2kvibkp4j3mjf/Prison_Break.S01.Ep1.Mp4.mp4/file	https://image.tmdb.org/t/p/w500/prisonBreakS1Poster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Prison Break S01 Ep 02	An engineer installs himself in a prison he helped design, in order to save his falsely accused brother from a death sentence.	Junior Giti	Action, Crime, Drama, Thriller	2640	2005	https://www.mediafire.com/file/psey66skvhlkwzc/Prison_Break_S01_Ep2_Mp4.mp4/file	https://image.tmdb.org/t/p/w500/prisonBreakS1Poster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Prison Break S01 Ep 03	An engineer installs himself in a prison he helped design, in order to save his falsely accused brother from a death sentence.	Junior Giti	Action, Crime, Drama, Thriller	2640	2005	https://www.mediafire.com/file/g7ys5rjp529kevf/Prison_Break_S01_Ep3_Mp4.mp4/file	https://image.tmdb.org/t/p/w500/prisonBreakS1Poster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Prison Break S01 Ep 04	An engineer installs himself in a prison he helped design, in order to save his falsely accused brother from a death sentence.	Junior Giti	Action, Crime, Drama, Thriller	2640	2005	https://www.mediafire.com/file/k021zg956h43is5/Prison_Break_S01ep4_Mp4.mp4/file	https://image.tmdb.org/t/p/w500/prisonBreakS1Poster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Prison Break S01 Ep 05	An engineer installs himself in a prison he helped design, in order to save his falsely accused brother from a death sentence.	Junior Giti	Action, Crime, Drama, Thriller	2640	2005	https://www.mediafire.com/file/m3xnf8cnzc36fsz/Prison_Break_S01_Ep5_Mp4.mp4/file	https://image.tmdb.org/t/p/w500/prisonBreakS1Poster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Prison Break S01 Ep 06	An engineer installs himself in a prison he helped design, in order to save his falsely accused brother from a death sentence.	Junior Giti	Action, Crime, Drama, Thriller	2640	2005	https://www.mediafire.com/file/er1gfdwxd5uwedo/Prison_Break_S01_Ep6_Mp4.mp4/file	https://image.tmdb.org/t/p/w500/prisonBreakS1Poster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Prison Break S01 Ep 07	An engineer installs himself in a prison he helped design, in order to save his falsely accused brother from a death sentence.	Junior Giti	Action, Crime, Drama, Thriller	2640	2005	https://www.mediafire.com/file/y9yf0e007cyjo9h/Prison_Break_S01_Ep7_Mp4.mp4/file	https://image.tmdb.org/t/p/w500/prisonBreakS1Poster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Prison Break S01 Ep 08	An engineer installs himself in a prison he helped design, in order to save his falsely accused brother from a death sentence.	Junior Giti	Action, Crime, Drama, Thriller	2640	2005	https://www.mediafire.com/file/9f46qvhuonjm86y/Prison_Break_S01_Ep_8_Mp4.mp4/file	https://image.tmdb.org/t/p/w500/prisonBreakS1Poster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Prison Break S01 Ep 09	An engineer installs himself in a prison he helped design, in order to save his falsely accused brother from a death sentence.	Junior Giti	Action, Crime, Drama, Thriller	2640	2005	https://www.mediafire.com/file/un9s54nkyl3jtyl/Prison_Beak_S01_Ep9_Mp4.mp4/file	https://image.tmdb.org/t/p/w500/prisonBreakS1Poster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Prison Break S01 Ep 10	An engineer installs himself in a prison he helped design, in order to save his falsely accused brother from a death sentence.	Junior Giti	Action, Crime, Drama, Thriller	2640	2005	https://www.mediafire.com/file/1anu3tn536x6fls/Prison_Break_S01_Ep10_Mp4.mp4/file	https://image.tmdb.org/t/p/w500/prisonBreakS1Poster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Prison Break S01 Ep 11	An engineer installs himself in a prison he helped design, in order to save his falsely accused brother from a death sentence.	Junior Giti	Action, Crime, Drama, Thriller	2640	2005	https://www.mediafire.com/file/jvbrbzy6bxpllqf/Prison_Break_S01_Ep11_Mp4.mp4/file	https://image.tmdb.org/t/p/w500/prisonBreakS1Poster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Prison Break S01 Ep 12	An engineer installs himself in a prison he helped design, in order to save his falsely accused brother from a death sentence.	Junior Giti	Action, Crime, Drama, Thriller	2640	2005	https://www.mediafire.com/file/nggzzdoi4dvy3u7/Prison_Break_S01_Ep12_Mp4.mp4/file	https://image.tmdb.org/t/p/w500/prisonBreakS1Poster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Prison Break S01 Ep 13	An engineer installs himself in a prison he helped design, in order to save his falsely accused brother from a death sentence.	Junior Giti	Action, Crime, Drama, Thriller	2640	2005	https://www.mediafire.com/file/ovytygh9bt11s4m/Prison_Break_S01_Ep13_Mp4.mp4/file	https://image.tmdb.org/t/p/w500/prisonBreakS1Poster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Prison Break S01 Ep 14	An engineer installs himself in a prison he helped design, in order to save his falsely accused brother from a death sentence.	Junior Giti	Action, Crime, Drama, Thriller	2640	2005	https://www.mediafire.com/file/6uwoefjz08gsn51/Prison_Break_S01_Ep14_Mp4.mp4/file	https://image.tmdb.org/t/p/w500/prisonBreakS1Poster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Prison Break S01 Ep 15	An engineer installs himself in a prison he helped design, in order to save his falsely accused brother from a death sentence.	Junior Giti	Action, Crime, Drama, Thriller	2640	2005	https://www.mediafire.com/file/6sxr5eozkxrg0xx/Prison_Break_S01_Ep15_Mp4.mp4/file	https://image.tmdb.org/t/p/w500/prisonBreakS1Poster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Prison Break S01 Ep 16	An engineer installs himself in a prison he helped design, in order to save his falsely accused brother from a death sentence.	Junior Giti	Action, Crime, Drama, Thriller	2640	2005	https://www.mediafire.com/file/clfe9352mvfd2b5/Prison_Break_S01_Ep16_Mp4.mp4/file	https://image.tmdb.org/t/p/w500/prisonBreakS1Poster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Prison Break S01 Ep 17	An engineer installs himself in a prison he helped design, in order to save his falsely accused brother from a death sentence.	Junior Giti	Action, Crime, Drama, Thriller	2640	2005	https://www.mediafire.com/file/j7mr99c1xfo1qra/Prison_Beak_S01_Ep17_Mp4_%25281%2529.mp4/file	https://image.tmdb.org/t/p/w500/prisonBreakS1Poster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Prison Break S01 Ep 18	An engineer installs himself in a prison he helped design, in order to save his falsely accused brother from a death sentence.	Junior Giti	Action, Crime, Drama, Thriller	2640	2005	https://www.mediafire.com/file/90bn00r0qdtw9fa/Prison_Break_S01_Ep_18_Mp4_%25281%2529.mp4/file	https://image.tmdb.org/t/p/w500/prisonBreakS1Poster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Prison Break S01 Ep 19	An engineer installs himself in a prison he helped design, in order to save his falsely accused brother from a death sentence.	Junior Giti	Action, Crime, Drama, Thriller	2640	2005	https://www.mediafire.com/file/g8gsbi2ciax9q2p/Prison_Break_S01_Ep19_Mp4.mp4/file	https://image.tmdb.org/t/p/w500/prisonBreakS1Poster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Prison Break S01 Ep 20	An engineer installs himself in a prison he helped design, in order to save his falsely accused brother from a death sentence.	Junior Giti	Action, Crime, Drama, Thriller	2640	2005	https://www.mediafire.com/file/ujb2jwgcwajz729/Prison_Break_S01_Ep20_Mp4.mp4/file	https://image.tmdb.org/t/p/w500/prisonBreakS1Poster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Prison Break S01 Ep 21	An engineer installs himself in a prison he helped design, in order to save his falsely accused brother from a death sentence.	Junior Giti	Action, Crime, Drama, Thriller	2640	2005	https://www.mediafire.com/file/shzau84jq2fx1gq/Prison_Break_S01_Ep21_Mp4.mp4/file	https://image.tmdb.org/t/p/w500/prisonBreakS1Poster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Prison Break S01 Ep 22 Final	An engineer installs himself in a prison he helped design, in order to save his falsely accused brother from a death sentence.	Junior Giti	Action, Crime, Drama, Thriller	2640	2005	https://www.mediafire.com/file/rzalybzahvzx7wy/Prison_Break_S01_Ep22_Final_Mp4.mp4/file	https://image.tmdb.org/t/p/w500/prisonBreakS1Poster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Who Is Erin Carter? S01 Ep 1	A British expat teacher living in Barcelona finds her tranquil life unraveling when she gets caught up in a violent supermarket robbery.	Junior Giti	Action, Adventure, Crime, Thriller	3000	2023	https://www.mediafire.com/file/tgahrfok747656m/Who_Is_Erin_Carter-_S01%252C_EP1.avi/file	https://image.tmdb.org/t/p/w500/whoIsErinCarterPoster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Who Is Erin Carter? S01 Ep 2	A British expat teacher living in Barcelona finds her tranquil life unraveling when she gets caught up in a violent supermarket robbery.	Junior Giti	Action, Adventure, Crime, Thriller	3000	2023	https://www.mediafire.com/file/wiamrv5ka8grn9z/Who_Is_Erin_Carter-_S01%252C_EP2.avi/file	https://image.tmdb.org/t/p/w500/whoIsErinCarterPoster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Who Is Erin Carter? S01 Ep 3	A British expat teacher living in Barcelona finds her tranquil life unraveling when she gets caught up in a violent supermarket robbery.	Junior Giti	Action, Adventure, Crime, Thriller	3000	2023	https://www.mediafire.com/file/y6lodhar8nj1fmg/Who_Is_Erin_Carter-_S01%252C_EP3.avi/file	https://image.tmdb.org/t/p/w500/whoIsErinCarterPoster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Who Is Erin Carter? S01 Ep 4	A British expat teacher living in Barcelona finds her tranquil life unraveling when she gets caught up in a violent supermarket robbery.	Junior Giti	Action, Adventure, Crime, Thriller	3000	2023	https://www.mediafire.com/file/b788r2wktl9kr7q/Who_Is_Erin_Carter-_S01%252C_EP4.avi/file	https://image.tmdb.org/t/p/w500/whoIsErinCarterPoster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Who Is Erin Carter? S01 Ep 5	A British expat teacher living in Barcelona finds her tranquil life unraveling when she gets caught up in a violent supermarket robbery.	Junior Giti	Action, Adventure, Crime, Thriller	3000	2023	https://www.mediafire.com/file/itep013otmaikhz/Who_Is_Erin_Carter-_S01%252C_EP5.avi/file	https://image.tmdb.org/t/p/w500/whoIsErinCarterPoster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Who Is Erin Carter? S01 Ep 6	A British expat teacher living in Barcelona finds her tranquil life unraveling when she gets caught up in a violent supermarket robbery.	Junior Giti	Action, Adventure, Crime, Thriller	3000	2023	https://www.mediafire.com/file/cdfwhxcdz3aaaa3/Who_Is_Erin_Carter-_S01%252C_EP6.mp4/file	https://image.tmdb.org/t/p/w500/whoIsErinCarterPoster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Who Is Erin Carter? S01 Ep 7 Final	A British expat teacher living in Barcelona finds her tranquil life unraveling when she gets caught up in a violent supermarket robbery.	Junior Giti	Action, Adventure, Crime, Thriller	3000	2023	https://www.mediafire.com/file/8wvges4rfn2gcmr/Who_Is_Erin_Carter-_S01%252C_EP7_.mp4/file	https://image.tmdb.org/t/p/w500/whoIsErinCarterPoster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com`;

const lines = rawData.trim().split('\n');
const csvLines = lines.map(line => {
  const parts = line.split('\t');
  return parts.map(p => `"${(p || '').trim().replace(/"/g, '""')}"`).join(',');
});

const targetPath = path.join(process.cwd(), 'movies.csv');
fs.appendFileSync(targetPath, '\n' + csvLines.join('\n'));
console.log(`Appended ${csvLines.length} Prison Break and Erin Carter episodes to movies.csv`);
