import fs from 'fs';
import path from 'path';

const tsvData = `The Vampire Diaries S01 Ep 01	A teenage girl is torn between two vampire brothers in the supernatural town of Mystic Falls, Virginia, uncovering centuries of buried secrets and danger.	Sankara da Premier	Drama, Fantasy, Horror, Mystery	2520	2009	https://www.mediafire.com/file/zk1v497hy8rn2fl/Vampire_dieries_S1_Ep1.mp4/file	https://image.tmdb.org/t/p/w500/vampireDiariesS1Poster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
The Vampire Diaries S01 Ep 02	A teenage girl is torn between two vampire brothers in the supernatural town of Mystic Falls, Virginia, uncovering centuries of buried secrets and danger.	Sankara da Premier	Drama, Fantasy, Horror, Mystery	2520	2009	https://www.mediafire.com/file/7tst43wf21b9x3l/Vampire_dieries_S1_Ep2.mp4/file	https://image.tmdb.org/t/p/w500/vampireDiariesS1Poster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
The Vampire Diaries S01 Ep 03	A teenage girl is torn between two vampire brothers in the supernatural town of Mystic Falls, Virginia, uncovering centuries of buried secrets and danger.	Sankara da Premier	Drama, Fantasy, Horror, Mystery	2520	2009	https://www.mediafire.com/file/wax2gn3o9042xxc/Vampire_dierlies_S1_Ep3.mp4/file	https://image.tmdb.org/t/p/w500/vampireDiariesS1Poster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
The Vampire Diaries S01 Ep 04	A teenage girl is torn between two vampire brothers in the supernatural town of Mystic Falls, Virginia, uncovering centuries of buried secrets and danger.	Sankara da Premier	Drama, Fantasy, Horror, Mystery	2520	2009	https://www.mediafire.com/file/vmvp68t6awihn5o/Vampire_dierlies_S1_Ep4.mp4/file	https://image.tmdb.org/t/p/w500/vampireDiariesS1Poster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
The Vampire Diaries S01 Ep 05	A teenage girl is torn between two vampire brothers in the supernatural town of Mystic Falls, Virginia, uncovering centuries of buried secrets and danger.	Sankara da Premier	Drama, Fantasy, Horror, Mystery	2520	2009	https://www.mediafire.com/file/62pcqxljo7ei43s/Vampire_dierlies_S1_Ep5.mp4/file	https://image.tmdb.org/t/p/w500/vampireDiariesS1Poster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
The Vampire Diaries S01 Ep 06	A teenage girl is torn between two vampire brothers in the supernatural town of Mystic Falls, Virginia, uncovering centuries of buried secrets and danger.	Sankara da Premier	Drama, Fantasy, Horror, Mystery	2520	2009	https://www.mediafire.com/file/1ox30iu2elyi4ry/Vampire_dierlies_S1_Ep6.mp4/file	https://image.tmdb.org/t/p/w500/vampireDiariesS1Poster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
The Vampire Diaries S01 Ep 07	A teenage girl is torn between two vampire brothers in the supernatural town of Mystic Falls, Virginia, uncovering centuries of buried secrets and danger.	Sankara da Premier	Drama, Fantasy, Horror, Mystery	2520	2009	https://www.mediafire.com/file/1t9gg4pqggfplq0/Vampire_dierlies_S1_Ep7.mp4/file	https://image.tmdb.org/t/p/w500/vampireDiariesS1Poster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
The Vampire Diaries S01 Ep 08	A teenage girl is torn between two vampire brothers in the supernatural town of Mystic Falls, Virginia, uncovering centuries of buried secrets and danger.	Sankara da Premier	Drama, Fantasy, Horror, Mystery	2520	2009	https://www.mediafire.com/file/3jwr33uqxgaa2gp/Vampire_dierlies_S1_Ep8.mp4/file	https://image.tmdb.org/t/p/w500/vampireDiariesS1Poster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
The Vampire Diaries S01 Ep 09	A teenage girl is torn between two vampire brothers in the supernatural town of Mystic Falls, Virginia, uncovering centuries of buried secrets and danger.	Sankara da Premier	Drama, Fantasy, Horror, Mystery	2520	2009	https://www.mediafire.com/file/hdqhtg5r3nyrdk7/Vampire_dierlies_S1_Ep9.mp4/file	https://image.tmdb.org/t/p/w500/vampireDiariesS1Poster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
The Vampire Diaries S01 Ep 10	A teenage girl is torn between two vampire brothers in the supernatural town of Mystic Falls, Virginia, uncovering centuries of buried secrets and danger.	Sankara da Premier	Drama, Fantasy, Horror, Mystery	2520	2009	https://www.mediafire.com/file/bcjb3i3w59h08y5/Vampire_dierlies_S1_Ep10.mp4/file	https://image.tmdb.org/t/p/w500/vampireDiariesS1Poster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
The Vampire Diaries S01 Ep 11	A teenage girl is torn between two vampire brothers in the supernatural town of Mystic Falls, Virginia, uncovering centuries of buried secrets and danger.	Sankara da Premier	Drama, Fantasy, Horror, Mystery	2520	2009	https://www.mediafire.com/file/e1t4o4ydptzmgyg/Vampire_dierlies_S1_Ep11.mp4/file	https://image.tmdb.org/t/p/w500/vampireDiariesS1Poster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
The Vampire Diaries S01 Ep 12	A teenage girl is torn between two vampire brothers in the supernatural town of Mystic Falls, Virginia, uncovering centuries of buried secrets and danger.	Sankara da Premier	Drama, Fantasy, Horror, Mystery	2520	2009	https://www.mediafire.com/file/bghts17mw5a2i46/Vampire_dierlies_S1_Ep12.mp4/file	https://image.tmdb.org/t/p/w500/vampireDiariesS1Poster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
The Vampire Diaries S01 Ep 13	A teenage girl is torn between two vampire brothers in the supernatural town of Mystic Falls, Virginia, uncovering centuries of buried secrets and danger.	Sankara da Premier	Drama, Fantasy, Horror, Mystery	2520	2009	https://www.mediafire.com/file/s2lxesnilo1y0d4/Vampire_dierlies_S1_Ep13.mp4/file	https://image.tmdb.org/t/p/w500/vampireDiariesS1Poster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
The Vampire Diaries S01 Ep 14	A teenage girl is torn between two vampire brothers in the supernatural town of Mystic Falls, Virginia, uncovering centuries of buried secrets and danger.	Sankara da Premier	Drama, Fantasy, Horror, Mystery	2520	2009	https://www.mediafire.com/file/vg05q32690f6tbl/Vampire_dierlies_S1_Ep14.mp4/file	https://image.tmdb.org/t/p/w500/vampireDiariesS1Poster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
The Vampire Diaries S01 Ep 15	A teenage girl is torn between two vampire brothers in the supernatural town of Mystic Falls, Virginia, uncovering centuries of buried secrets and danger.	Sankara da Premier	Drama, Fantasy, Horror, Mystery	2520	2009	https://www.mediafire.com/file/1y24b487m70wr0h/Vampire_dierlies_S1_Ep15.mp4/file	https://image.tmdb.org/t/p/w500/vampireDiariesS1Poster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
The Vampire Diaries S01 Ep 16	A teenage girl is torn between two vampire brothers in the supernatural town of Mystic Falls, Virginia, uncovering centuries of buried secrets and danger.	Sankara da Premier	Drama, Fantasy, Horror, Mystery	2520	2009	https://www.mediafire.com/file/0pczq7rjdgs4fu4/Vampire_dierlies_S1_Ep16.mp4/file	https://image.tmdb.org/t/p/w500/vampireDiariesS1Poster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
The Vampire Diaries S01 Ep 17	A teenage girl is torn between two vampire brothers in the supernatural town of Mystic Falls, Virginia, uncovering centuries of buried secrets and danger.	Sankara da Premier	Drama, Fantasy, Horror, Mystery	2520	2009	https://www.mediafire.com/file/p3q0iodc9yj5ht4/Vampire_dierlies_S1_Ep17.mp4/file	https://image.tmdb.org/t/p/w500/vampireDiariesS1Poster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
The Vampire Diaries S01 Ep 18	A teenage girl is torn between two vampire brothers in the supernatural town of Mystic Falls, Virginia, uncovering centuries of buried secrets and danger.	Sankara da Premier	Drama, Fantasy, Horror, Mystery	2520	2009	https://www.mediafire.com/file/andiqgvuo6mqfor/Vampire_dierlies_S1_Ep18.mp4/file	https://image.tmdb.org/t/p/w500/vampireDiariesS1Poster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
The Vampire Diaries S01 Ep 19	A teenage girl is torn between two vampire brothers in the supernatural town of Mystic Falls, Virginia, uncovering centuries of buried secrets and danger.	Sankara da Premier	Drama, Fantasy, Horror, Mystery	2520	2009	https://www.mediafire.com/file/fsvfdl7n79xb8ay/Vampire_deirlies_S1_Ep19.mp4/file	https://image.tmdb.org/t/p/w500/vampireDiariesS1Poster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
The Vampire Diaries S01 Ep 20	A teenage girl is torn between two vampire brothers in the supernatural town of Mystic Falls, Virginia, uncovering centuries of buried secrets and danger.	Sankara da Premier	Drama, Fantasy, Horror, Mystery	2520	2009	https://www.mediafire.com/file/oir4s4euxhhhxoh/Vampire_deirlies_S1_Ep20.mp4/file	https://image.tmdb.org/t/p/w500/vampireDiariesS1Poster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
The Vampire Diaries S01 Ep 21	A teenage girl is torn between two vampire brothers in the supernatural town of Mystic Falls, Virginia, uncovering centuries of buried secrets and danger.	Sankara da Premier	Drama, Fantasy, Horror, Mystery	2520	2009	https://www.mediafire.com/file/mtph91nhkc7ezx0/Vampire_Dierlies_S1_Ep21.mp4/file	https://image.tmdb.org/t/p/w500/vampireDiariesS1Poster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
The Vampire Diaries S01 Ep 22 Final	A teenage girl is torn between two vampire brothers in the supernatural town of Mystic Falls, Virginia, uncovering centuries of buried secrets and danger.	Sankara da Premier	Drama, Fantasy, Horror, Mystery	2520	2009	https://www.mediafire.com/file/53y00v2cqbgpzxi/Vampire_dieries_S1_Ep22.mp4/file	https://image.tmdb.org/t/p/w500/vampireDiariesS1Poster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Olympus Has Fallen	Secret Service agent Mike Banning finds himself trapped inside the White House in the wake of a terrorist attack and must work with national security to rescue the President.	Sankara da Premier	Action, Thriller	7140	2013	https://www.mediafire.com/file/hf0fhh092r18mbm/Olympus_Has_Fallen_%25282023%2529.mp4/file	https://image.tmdb.org/t/p/w500/olympusHasFallenPoster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
London Has Fallen	In London for the Prime Minister's funeral, Mike Banning discovers a plot to assassinate all the attending world leaders.	Sankara da Premier	Action, Thriller	5940	2016	https://www.mediafire.com/file/wwuybs7uq6e4ww4/London_Has_Fallen.mp4/file	https://image.tmdb.org/t/p/w500/londonHasFallenPoster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
The Prisoner Ep 1	A man resigns from his secret government position, only to wake up trapped in a mysterious and bizarre coastal village where residents are identified by numbers.	Sankara da Premier	Drama, Mystery, Sci-Fi	2700	2026	https://www.mediafire.com/file/rx7531rhcuvza9q/THE_PRISOBER_EP1.mp4/file	https://image.tmdb.org/t/p/w500/thePrisonerSeriesPoster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
The Prisoner Ep 2	A man resigns from his secret government position, only to wake up trapped in a mysterious and bizarre coastal village where residents are identified by numbers.	Sankara da Premier	Drama, Mystery, Sci-Fi	2700	2026	https://www.mediafire.com/file/3qy2wljk8j3xwm5/Watch_Prisoner_Ep2_%25282026%2529.mp4/file	https://image.tmdb.org/t/p/w500/thePrisonerSeriesPoster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
The Prisoner Ep 3	A man resigns from his secret government position, only to wake up trapped in a mysterious and bizarre coastal village where residents are identified by numbers.	Sankara da Premier	Drama, Mystery, Sci-Fi	2700	2026	https://www.mediafire.com/file/sw6d8g34zt7zp5t/Watch_Prisoner_Ep3_%25282026%2529.mp4/file	https://image.tmdb.org/t/p/w500/thePrisonerSeriesPoster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
The Prisoner Ep 4	A man resigns from his secret government position, only to wake up trapped in a mysterious and bizarre coastal village where residents are identified by numbers.	Sankara da Premier	Drama, Mystery, Sci-Fi	2700	2026	https://www.mediafire.com/file/jyqyfvynpeusl1h/Watch_Prisoner_Ep4_%25282026%2529.mp4/file	https://image.tmdb.org/t/p/w500/thePrisonerSeriesPoster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
The Prisoner Ep 5	A man resigns from his secret government position, only to wake up trapped in a mysterious and bizarre coastal village where residents are identified by numbers.	Sankara da Premier	Drama, Mystery, Sci-Fi	2700	2026	https://www.mediafire.com/file/iibkadkhz0b3flk/Watch_Prisoner_Ep5_%25282026%2529.mp4/file	https://image.tmdb.org/t/p/w500/thePrisonerSeriesPoster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
The Prisoner Ep 6 Final	A man resigns from his secret government position, only to wake up trapped in a mysterious and bizarre coastal village where residents are identified by numbers.	Sankara da Premier	Drama, Mystery, Sci-Fi	2700	2026	https://www.mediafire.com/file/4pb161afzfglt38/Prisoner_Ep6_Final_%25282026%2529.mp4/file	https://image.tmdb.org/t/p/w500/thePrisonerSeriesPoster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
They Will Kill You	A woman takes a housekeeping job at a mysterious high-rise in New York City, only to discover a community of residents involved in dark occult disappearances.	Sankara da Premier	Horror, Mystery, Thriller	5700	2025	https://www.mediafire.com/file/mcwvyj162t1w4tt/They_will_kill_you_.mp4/file	https://image.tmdb.org/t/p/w500/theyWillKillYouPoster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Watching You Ep 1	A young woman's life spirals out of control when she discovers an anonymous voyeur has bugged her apartment and is manipulating every aspect of her reality.	Sankara da Premier	Mystery, Thriller	2700	2026	https://www.mediafire.com/file/4opd9y1to4yoq5g/WATCHING_YOU_E01.mp4/file	https://image.tmdb.org/t/p/w500/watchingYouSeriesPoster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Watching You Ep 2	A young woman's life spirals out of control when she discovers an anonymous voyeur has bugged her apartment and is manipulating every aspect of her reality.	Sankara da Premier	Mystery, Thriller	2700	2026	https://www.mediafire.com/file/7vqolp8r2pg7pe2/Watching_you_%25282026%2529_Ep2.mp4/file	https://image.tmdb.org/t/p/w500/watchingYouSeriesPoster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Watching You Ep 3	A young woman's life spirals out of control when she discovers an anonymous voyeur has bugged her apartment and is manipulating every aspect of her reality.	Sankara da Premier	Mystery, Thriller	2700	2026	https://www.mediafire.com/file/aq6b5o7q41y1qcm/Watching_you_Ep3_%25282026%2529.mp4/file	https://image.tmdb.org/t/p/w500/watchingYouSeriesPoster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Watching You Ep 4	A young woman's life spirals out of control when she discovers an anonymous voyeur has bugged her apartment and is manipulating every aspect of her reality.	Sankara da Premier	Mystery, Thriller	2700	2026	https://www.mediafire.com/file/51np97w1lj7ss1i/Watching_you_Ep4%25282026%2529.mp4/file	https://image.tmdb.org/t/p/w500/watchingYouSeriesPoster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Watching You Ep 5	A young woman's life spirals out of control when she discovers an anonymous voyeur has bugged her apartment and is manipulating every aspect of her reality.	Sankara da Premier	Mystery, Thriller	2700	2026	https://www.mediafire.com/file/fktox2hocvtf7z3/Watching_you_Ep5_%25282026%2529.mp4/file	https://image.tmdb.org/t/p/w500/watchingYouSeriesPoster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Watching You Ep 6 Final	A young woman's life spirals out of control when she discovers an anonymous voyeur has bugged her apartment and is manipulating every aspect of her reality.	Sankara da Premier	Mystery, Thriller	2700	2026	https://www.mediafire.com/file/vicplpv9rf0t9nm/Watching_you_Ep6_%25282026%2529.mp4/file	https://image.tmdb.org/t/p/w500/watchingYouSeriesPoster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Ant-Man	Armed with a super-suit with the astonishing ability to shrink in scale but increase in strength, cat burglar Scott Lang must embrace his inner hero.	Sankara da Premier	Action, Adventure, Comedy, Sci-Fi	7020	2015	https://www.mediafire.com/file/l7rd98em38s9xjz/Anti_Man_1_Hd_Mp4.mp4/file	https://image.tmdb.org/t/p/w500/antManPoster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Ice Fall	A young Indigenous game warden and an eccentric tracker race against time when a plane carrying illicit contraband crashes deep in a frozen, treacherous wilderness.	Sankara da Premier	Action, Crime, Thriller	5880	2025	https://www.mediafire.com/file/p26c9xo2lfmljpm/Ice_Fall_2025.mp4/file	https://image.tmdb.org/t/p/w500/iceFallPosterPath500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Cruel War	A band of veteran soldiers finds themselves trapped behind enemy lines in a ruthless war zone, forced to make impossible moral choices to save innocent lives.	Sankara da Premier	Action, Drama, War	5520	2024	https://www.mediafire.com/file/i73td307nfcbtkh/CRUEL_WAR.mp4/file	https://image.tmdb.org/t/p/w500/cruelWarPosterPath500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Desperate Lies Ep 1	Due to a rare phenomenon, a woman finds herself pregnant with twins by two different men. Over time, she struggles to keep her family together and her secrets hidden.	Sankara da Premier	Drama, Romance	2820	2024	https://www.mediafire.com/file/b26qjisnmfqdcza/Desperate_Lies_Ep1.mp4/file	https://image.tmdb.org/t/p/w500/desperateLiesNetflixPoster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Desperate Lies Ep 2	Due to a rare phenomenon, a woman finds herself pregnant with twins by two different men. Over time, she struggles to keep her family together and her secrets hidden.	Sankara da Premier	Drama, Romance	2820	2024	https://www.mediafire.com/file/qpqxor7k1v3b2g7/Desperate_Lies_ep2.mp4/file	https://image.tmdb.org/t/p/w500/desperateLiesNetflixPoster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Desperate Lies Ep 3	Due to a rare phenomenon, a woman finds herself pregnant with twins by two different men. Over time, she struggles to keep her family together and her secrets hidden.	Sankara da Premier	Drama, Romance	2820	2024	https://www.mediafire.com/file/jyjxt4omf9o6m9i/Desperate_Lies_ep3.mp4/file	https://image.tmdb.org/t/p/w500/desperateLiesNetflixPoster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Desperate Lies Ep 4	Due to a rare phenomenon, a woman finds herself pregnant with twins by two different men. Over time, she struggles to keep her family together and her secrets hidden.	Sankara da Premier	Drama, Romance	2820	2024	https://www.mediafire.com/file/rkjbkbfh79cgzpv/Desperate_Lies_ep_4.mp4/file	https://image.tmdb.org/t/p/w500/desperateLiesNetflixPoster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Maleficent	A vengeful fairy is driven to curse an infant princess, only to discover that the child may be the only one who can restore peace to their troubled land.	Sankara da Premier	Action, Adventure, Family, Fantasy	5820	2014	https://www.mediafire.com/file/ygqwxgu0lwx0q2x/Malficent_Sankra.mp4/file	https://image.tmdb.org/t/p/w500/maleficentPoster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Horse War One	During turbulent tribal warfare in historical Asia, horse-mounted cavalry warriors engage in a ferocious tactical showdown to secure kingdom borders.	Sankara da Premier	Action, History, War	5640	2024	https://www.mediafire.com/file/6ppviht5xv6xs7c/1.HORSEWAR_ONE.mp4/file	https://image.tmdb.org/t/p/w500/horseWarOnePoster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Final Destination: Bloodlines	Plagued by premonitions of a violent collapse, Stefani returns home to uncover the origins of Death's relentless design targeting her family line.	Sankara da Premier	Horror, Mystery	6300	2025	https://www.mediafire.com/file/rkx9xa9enxtqknv/Final_Destination_Bloodline_SANKRA.mp4/file	https://image.tmdb.org/t/p/w500/finalDestinationBloodlines500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Gunpowder Milkshake	Three generations of women fight back against those who could take everything from them in the span of one fateful night.	Sankara da Premier	Action, Crime, Thriller	6840	2021	https://www.mediafire.com/file/vli13ahik90uz9c/Watch_Gunpowder_Milkshake.mp4/file	https://image.tmdb.org/t/p/w500/gunpowderMilkshakePoster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Sixty Minutes	Desperate not to lose custody of his daughter, a mixed martial arts fighter makes dangerous enemies when he abandons a matchup to race across Berlin.	Sankara da Premier	Action, Drama, Sport	5340	2024	https://www.mediafire.com/file/oondayeaan22i6y/Watch_Sixty_Minutes_2024.mp4/file	https://image.tmdb.org/t/p/w500/sixtyMinutesPoster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
War of the Arrows	A master Korean archer takes on the mighty Qing dynasty forces to rescue his kidnapped sister during the second Manchu invasion of Korea.	Sankara da Premier	Action, Adventure, History	7320	2011	https://www.mediafire.com/file/dbaay4mgrrmizx0/Wars_Of_The_Arrows.mp4/file	https://image.tmdb.org/t/p/w500/warOfTheArrowsPoster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
After Earth - Part A	A crash landing leaves Kitai Raige and his father Cypher stranded on Earth, a millennium after events forced humanity's escape. With Cypher injured, Kitai must embark on a perilous journey to signal for help.	Sankara da Premier	Action, Adventure, Sci-Fi	3000	2013	https://www.mediafire.com/file/2gu7spy7ii13x6x/After_Earth_A.mp4/file	https://image.tmdb.org/t/p/w500/afterEarthPoster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
After Earth - Part B	A crash landing leaves Kitai Raige and his father Cypher stranded on Earth, a millennium after events forced humanity's escape. With Cypher injured, Kitai must embark on a perilous journey to signal for help.	Sankara da Premier	Action, Adventure, Sci-Fi	3000	2013	https://www.mediafire.com/file/mt4lzka9kjzqmic/After_Earth_B.mp4/file	https://image.tmdb.org/t/p/w500/afterEarthPoster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com`;

const targetPath = path.join(process.cwd(), 'movies.csv');
const existingCsv = fs.readFileSync(targetPath, 'utf8');

const newLines = tsvData.trim().split('\n').map(line => {
  const parts = line.split('\t');
  return parts.map(p => `"${(p || '').trim().replace(/"/g, '""')}"`).join(',');
});

let appended = 0;
for (const line of newLines) {
  const titleMatch = line.match(/^"([^"]+)"/);
  const title = titleMatch ? titleMatch[1] : '';
  if (!existingCsv.includes(`"${title}"`)) {
    fs.appendFileSync(targetPath, '\n' + line);
    appended++;
  }
}

console.log(`Appended ${appended} new records from batch 2 to movies.csv.`);
