import fs from 'fs';
import path from 'path';

const tsvData = `Umthetho Ep 1	A gritty South African crime drama revolving around township justice, police corruption, and a community caught between law and survival.	Savimbi	Action, Crime, Drama	2700	2024	https://www.mediafire.com/file/czd92hs2dsy7550/UMTHETHO_1_1.mp4/file	https://image.tmdb.org/t/p/w500/umthethoSeriesPoster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Umthetho Ep 2	A gritty South African crime drama revolving around township justice, police corruption, and a community caught between law and survival.	Savimbi	Action, Crime, Drama	2700	2024	https://www.mediafire.com/file/0v9wupp3os1bysi/UMTHETHO_2_1.mp4/file	https://image.tmdb.org/t/p/w500/umthethoSeriesPoster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Umthetho Ep 3	A gritty South African crime drama revolving around township justice, police corruption, and a community caught between law and survival.	Savimbi	Action, Crime, Drama	2700	2024	https://www.mediafire.com/file/feilh2h4we3s8qe/UMUTHETHO_EP3.mp4/file	https://image.tmdb.org/t/p/w500/umthethoSeriesPoster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Umthetho Ep 4	A gritty South African crime drama revolving around township justice, police corruption, and a community caught between law and survival.	Savimbi	Action, Crime, Drama	2700	2024	https://www.mediafire.com/file/hq1irhqiaocffkc/UMUTHETHO_EP4.mp4/file	https://image.tmdb.org/t/p/w500/umthethoSeriesPoster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Umthetho Ep 5 Final	A gritty South African crime drama revolving around township justice, police corruption, and a community caught between law and survival.	Savimbi	Action, Crime, Drama	2700	2024	https://www.mediafire.com/file/40590kts0f54hvt/UMTHETHO_5.mp4/file	https://image.tmdb.org/t/p/w500/umthethoSeriesPoster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Brotherhood - Part A	Twin brothers find themselves on opposite sides of the law in Lagos when armed robberies and political corruption collide in violent street battles.	Savimbi	Action, Crime, Drama	3600	2022	https://www.mediafire.com/file/58bsw2gpvsabaj7/BROTHERHOOD_A_1.mp4/file	https://image.tmdb.org/t/p/w500/brotherhoodNollywoodPoster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Brotherhood - Part B	Twin brothers find themselves on opposite sides of the law in Lagos when armed robberies and political corruption collide in violent street battles.	Savimbi	Action, Crime, Drama	3600	2022	https://www.mediafire.com/file/7dfe2w612gmla47/BROTHERHOOD_B_1.mp4/file	https://image.tmdb.org/t/p/w500/brotherhoodNollywoodPoster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
The Lone Ranger - Part A	Native American warrior Tonto recounts the untold tales that transformed John Reid, a man of the law, into a legend of justice.	Savimbi	Action, Adventure, Western	4470	2013	https://www.mediafire.com/file/d8yvhfj22qb3d2j/THE_LONE_RANGER_A.mp4/file	https://image.tmdb.org/t/p/w500/loneRangerPoster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
The Lone Ranger - Part B	Native American warrior Tonto recounts the untold tales that transformed John Reid, a man of the law, into a legend of justice.	Savimbi	Action, Adventure, Western	4470	2013	https://www.mediafire.com/file/6u84a7f9xmxrerc/THE_LONE_RANGER_B.mp4/file	https://image.tmdb.org/t/p/w500/loneRangerPoster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Red Dawn	A group of teenagers look to save their town and their country from a surprise invasion by North Korean military forces.	Savimbi	Action, Sci-Fi, Thriller	5580	2012	https://www.mediafire.com/file/v33lvclo2itmxhz/Red_Dawn_Hd.mp4/file	https://image.tmdb.org/t/p/w500/redDawn2012Poster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Bilal: A New Breed of Hero - Part A	A thousand years ago, a boy with dreams of becoming a great warrior is abducted with his sister and thrown into a world where greed and injustice rule all.	Savimbi	Animation, Action, Adventure, Biography	3150	2015	https://www.mediafire.com/file/2z3gmczapjnckgq/Bilal_Hd.mp4/file	https://image.tmdb.org/t/p/w500/bilalPoster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Bilal: A New Breed of Hero - Part B	A thousand years ago, a boy with dreams of becoming a great warrior is abducted with his sister and thrown into a world where greed and injustice rule all.	Savimbi	Animation, Action, Adventure, Biography	3150	2015	https://www.mediafire.com/file/3frcjl5an97kh0c/Bilal_B.mp4/file	https://image.tmdb.org/t/p/w500/bilalPoster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Like Stars on Earth (Taare Zameen Par)	An eight-year-old boy is thought to be a lazy trouble-maker, until the new art teacher has the patience and compassion to discover the real problem behind his struggles in school.	Savimbi	Drama, Family	9900	2007	https://www.mediafire.com/file/khkcmu07zepnrsy/Like_Stars_On_Earth_Hd.mp4/file	https://image.tmdb.org/t/p/w500/taareZameenParPoster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
PK - Part A	An alien on Earth loses the only device he can use to communicate with his spaceship. His innocent nature and child-like questions force the country to re-evaluate their religious dogmas.	Savimbi	Comedy, Drama, Sci-Fi	4590	2014	https://www.mediafire.com/file/jd2b4s2ihr7b8l9/Pk_A_By_Savimb.mp4/file	https://image.tmdb.org/t/p/w500/pkMoviePoster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
PK - Part B	An alien on Earth loses the only device he can use to communicate with his spaceship. His innocent nature and child-like questions force the country to re-evaluate their religious dogmas.	Savimbi	Comedy, Drama, Sci-Fi	4590	2014	https://www.mediafire.com/file/xv42ppf9z015kgr/Pk_B_By_Savimb.mp4/file	https://image.tmdb.org/t/p/w500/pkMoviePoster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
The Great Battle	A historical siege drama recounting the heroic 88-day battle that Yang Man-chun and his Goguryeo troops fought against 500,000 invading Tang dynasty forces.	Savimbi	Action, Drama, History, War	8160	2018	https://www.mediafire.com/file/roqw5cxjhuowwc0/THE_GREAT_BATTLE.mp4/file	https://image.tmdb.org/t/p/w500/theGreatBattlePoster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
The Boy Who Harnessed the Wind	Against all the odds, a thirteen-year-old boy in Malawi invents an unconventional way to save his family and village from famine by building a wind turbine from scrap parts.	Savimbi	Biography, Drama, History	6780	2019	https://www.mediafire.com/file/8ql9kn7iredcqxa/The_Boy_Who_Harnsed_The_Wind.mp4/file	https://image.tmdb.org/t/p/w500/boyWhoHarnessedTheWindPoster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Io Capitano	Two young Senegalese men leave Dakar on an arduous, dangerous voyage across Africa to reach Europe in search of a brighter future.	Savimbi	Drama	7320	2023	https://www.mediafire.com/file/nk56i3xn1guuceh/LO_CAPITANO.mp4/file	https://image.tmdb.org/t/p/w500/ioCapitanoPoster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Rebel Ridge - Part A	A former Marine confronts corruption in a small American town when local law enforcement unjustly seizes the bag of cash he needs to post his cousin's bail.	Savimbi	Action, Crime, Drama, Thriller	3930	2024	https://www.mediafire.com/file/go0n2ta0b7ue6zl/Rebel_Ridge_trans_A.mp4/file	https://image.tmdb.org/t/p/w500/rebelRidgePoster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Rebel Ridge - Part B	A former Marine confronts corruption in a small American town when local law enforcement unjustly seizes the bag of cash he needs to post his cousin's bail.	Savimbi	Action, Crime, Drama, Thriller	3930	2024	https://www.mediafire.com/file/9xrw3uoxjkk9pp6/Rebel_Ridge_TRANS_B.mp4/file	https://image.tmdb.org/t/p/w500/rebelRidgePoster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Moonfall	A mysterious force knocks the Moon from its orbit around Earth and sends it hurtling on a collision course with life as we know it.	Savimbi	Action, Adventure, Sci-Fi	7800	2022	https://www.mediafire.com/file/nbfk9eu7xp9ip3n/MOONFALL.mp4/file	https://image.tmdb.org/t/p/w500/moonfallPoster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
The Tourist	Frank, an American tourist visiting Italy to mend a broken heart, becomes entangled in a dangerous web of intrigue orchestrated by an enigmatic woman named Elise.	Savimbi	Action, Crime, Mystery, Romance	6180	2010	https://drive.google.com/file/d/1PdV3tqFIJiFt4O_RtlKBklsulJkXXoxg/view?usp=sharing	https://image.tmdb.org/t/p/w500/theTouristPoster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
The Berlin File	A South Korean intelligence agent discovers an unregistered North Korean operative during an illegal arms deal in Berlin, plunging them into a web of betrayal.	Savimbi	Action, Drama, Thriller	7200	2013	https://drive.google.com/file/d/1eSuP5QQAj2VrHyQSZtz_M3E20rxdXnRE/view?usp=sharing	https://image.tmdb.org/t/p/w500/theBerlinFilePoster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Who Am I? - Part A	A top secret agent loses his memory after falling from a helicopter crash in South Africa. He is chased by other agency operatives while trying to discover his true identity.	Yanga	Action, Adventure, Comedy	3600	1998	https://www.mediafire.com/file/qgs4fcwcnt7u076/Who_Am_I_A_Hd.mp4/file	https://image.tmdb.org/t/p/w500/whoAmIJackieChanPoster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Who Am I? - Part B	A top secret agent loses his memory after falling from a helicopter crash in South Africa. He is chased by other agency operatives while trying to discover his true identity.	Yanga	Action, Adventure, Comedy	3600	1998	https://www.mediafire.com/file/expor2xmx9uyoeq/Who_Am_I_B_Hd.mp4/file	https://image.tmdb.org/t/p/w500/whoAmIJackieChanPoster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Wrong Turn 4: Bloody Beginnings	A group of college friends get lost in a snowstorm and take shelter in an abandoned sanatorium, unaware that three cannibalistic hillbillies still live there.	Yanga	Horror	5580	2011	https://www.mediafire.com/file/rjjd63cttpg2cum/Wrong_Turn_4_Hd.mp4/file	https://image.tmdb.org/t/p/w500/wrongTurn4Poster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Wrong Turn 3: Left for Dead	Fong and a group of escaped convicts find themselves hunted by mutated mountain man Three Finger in the West Virginia backwoods.	Yanga	Horror	5520	2009	https://www.mediafire.com/file/yvlccok61kkn2st/Wrong_Turn_3_Hd.mp4/file	https://image.tmdb.org/t/p/w500/wrongTurn3Poster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Wrong Turn 2: Dead End	A group of reality show contestants find themselves fighting for survival against a family of inbred, deformed cannibals in the deep woods.	Yanga	Horror	5760	2007	https://www.mediafire.com/file/rq3h7nkrih78iut/Wrong_Turn_2_Hd.mp4/file	https://image.tmdb.org/t/p/w500/wrongTurn2Poster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Wrong Turn	Six people find themselves stranded in the woods of West Virginia, where they are hunted by a trio of disfigured, cannibalistic mountain men.	Yanga	Horror	5040	2003	https://www.mediafire.com/file/73lnwx8rphgdth5/Wrong_Turn_1_Hd_Mp4.mp4/file	https://image.tmdb.org/t/p/w500/wrongTurn1Poster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Gallowwalkers - Part A	A cursed gunslinger whose victims return from the dead recruits a young warrior to help him battle an army of undead outlaws.	Yanga	Action, Fantasy, Horror, Western	2700	2012	https://www.mediafire.com/file/divjm2ugqhhqucf/Gallowwalkers.A._Hd.Mp4.mp4/file	https://image.tmdb.org/t/p/w500/gallowwalkersPoster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Gallowwalkers - Part B	A cursed gunslinger whose victims return from the dead recruits a young warrior to help him battle an army of undead outlaws.	Yanga	Action, Fantasy, Horror, Western	2700	2012	https://www.mediafire.com/file/m0w4c06c2fmbhsj/Gallowwalkers.B._Hd.Mp4.mp4/file	https://image.tmdb.org/t/p/w500/gallowwalkersPoster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Ninja Assassin	A rogue orphan ninja breaks away from the deadly Ozunu Clan that raised him and partners with an Europol agent to bring down his former masters.	Yanga	Action, Thriller	5940	2009	https://www.mediafire.com/file/4qsb40hhfahtpnu/Ninja_Assassin__Hd_.mp4/file	https://image.tmdb.org/t/p/w500/ninjaAssassinPoster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Ip Man 2	Wing Chun master Ip Man moves to Hong Kong in the 1950s, where he attempts to promote his discipline while encountering fierce rivalry from local masters and a corrupt British boxing champion.	Yanga	Action, Biography, Drama	6480	2010	https://www.mediafire.com/file/5csjnc7584knjk4/Ip_Man_2_Hd.mp4/file	https://image.tmdb.org/t/p/w500/ipMan2Poster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Iceman (2014)	A Ming Dynasty palace guard and his fellow warriors are frozen in time during an avalanche, only to awaken 400 years later in modern Hong Kong to settle an ancient score.	Yanga	Action, Comedy, History, Sci-Fi	6240	2014	https://www.mediafire.com/file/0sccqb8hrq38jue/ICEMAN__1_HD.mp4/file	https://image.tmdb.org/t/p/w500/iceman2014Poster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Dragon (Wu Xia)	A papermaker who seems like a quiet family man becomes the target of an inquisitive detective after expertly killing two vicious bandits in self-defense.	Yanga	Action, Drama, Mystery	5880	2011	https://www.mediafire.com/file/e8i3qgda2kdig4p/Wuxia_Hd.mp4/file	https://image.tmdb.org/t/p/w500/wuXiaDragonPoster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
The Tournament	Every ten years, thirty of the world's deadliest assassins gather in an unsuspecting English town for an ultra-violent, televised battle royale.	Yanga	Action, Thriller	5700	2009	https://www.mediafire.com/file/s0dmp43mph1bcu2/The_Tournament_Hd_Mp4.mp4/file	https://image.tmdb.org/t/p/w500/theTournamentPoster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Police Story 3: Supercop	A Hong Kong detective is paired with an ambitious Mainland female inspector to infiltrate and dismantle a ruthless drug cartel spanning Hong Kong and Southeast Asia.	Yanga	Action, Comedy, Crime, Thriller	5760	1992	https://www.mediafire.com/file/ntlrguhsiq0fj21/Police_Story_Hd_Yanga.mp4/file	https://image.tmdb.org/t/p/w500/policeStory3SupercopPoster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Evil Dead (2013) - Part A	Five friends travel to a remote cabin in the woods, where their discovery of a Book of the Dead unwittingly summons dormant demons living in the nearby woods.	Yanga	Horror	2730	2013	https://www.mediafire.com/file/i766amokzfhda39/Evil_Dead_A.mp4/file	https://image.tmdb.org/t/p/w500/evilDead2013Poster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Evil Dead (2013) - Part B	Five friends travel to a remote cabin in the woods, where their discovery of a Book of the Dead unwittingly summons dormant demons living in the nearby woods.	Yanga	Horror	2730	2013	https://www.mediafire.com/file/o3f5j8n0op4ebao/Evil_Dead_B.mp4/file	https://image.tmdb.org/t/p/w500/evilDead2013Poster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
True Legend - Part A	Su Qi-Er retires from dynastic military duty to pursue his dream of founding a martial arts school, but is betrayed by his vengeful stepbrother using dark techniques.	Yanga	Action, History	2300	2010	https://www.mediafire.com/file/la15tmfe4hnldpb/True_Legend_A.mp4/file	https://image.tmdb.org/t/p/w500/trueLegendPoster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
True Legend - Part B	Su Qi-Er retires from dynastic military duty to pursue his dream of founding a martial arts school, but is betrayed by his vengeful stepbrother using dark techniques.	Yanga	Action, History	2300	2010	https://www.mediafire.com/file/if5g00lfjbexb2u/True_Legend_B.mp4/file	https://image.tmdb.org/t/p/w500/trueLegendPoster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
True Legend - Part C	Su Qi-Er retires from dynastic military duty to pursue his dream of founding a martial arts school, but is betrayed by his vengeful stepbrother using dark techniques.	Yanga	Action, History	2300	2010	https://www.mediafire.com/file/9bpqt767xcbfxd0/True_Legend_C.mp4/file	https://image.tmdb.org/t/p/w500/trueLegendPoster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Lone Survivor	Marcus Luttrell and his team set out on a mission to capture or kill notorious Taliban leader Ahmad Shah, in late June 2005, facing overwhelming odds in the Hindu Kush mountains.	Yanga	Action, Biography, Drama, War	7260	2013	https://www.mediafire.com/file/rr6v3sb9x571aum/Lone_Survivor_Full_Hd.mp4/file	https://image.tmdb.org/t/p/w500/loneSurvivorPoster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Kung Fu Dunk	An orphaned boy with extraordinary martial arts agility is recruited by an ambitious hustler to join a college basketball team, creating impossible court acrobatics.	Yanga	Action, Comedy, Sport	6000	2008	https://drive.google.com/file/d/14nzu-529Iw9JWo86BILVrpyYQ-L5SfzM/view?usp=sharing	https://image.tmdb.org/t/p/w500/kungFuDunkPoster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
5 Days of War	An American journalist, his cameraman, and a local woman find themselves caught in the crossfire during the 2008 military conflict between Russia and Georgia.	Yanga	Action, Drama, War	6780	2011	https://drive.google.com/file/d/1ocUzlJhP8RdmV-QpOZ2SRFR45VJwMFtC/view?usp=sharing	https://image.tmdb.org/t/p/w500/fiveDaysOfWarPoster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Wheels on Meals	Two Chinese cousins running a mobile fast-food van in Barcelona team up with a bumbling private investigator to rescue a pickpocket heiress from a ruthless count.	Yanga	Action, Comedy, Romance	6480	1984	https://www.mediafire.com/file/lwzms0slidzju8i/WEELS_ON_MEALS.mp4/file	https://image.tmdb.org/t/p/w500/wheelsOnMealsPoster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Desire (Tikuvutu)	A passionate romantic drama following two individuals whose forbidden mutual attraction causes catastrophic ripples across their families and social circles.	Genius	Drama, Romance	5400	2024	https://www.mediafire.com/file/bvtie8e6q8ynzmq/Desire_Tikuvutu_-_Genius.mp4/file	https://image.tmdb.org/t/p/w500/desireTikuvutuPoster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Firebreak	Wildland smokejumpers and urban firefighters race to establish a containment perimeter when an unprecedented firestorm traps a community inside a mountain canyon.	Genius	Action, Drama, Thriller	5880	2024	https://www.mediafire.com/file/ueh9giw4mluk7th/Firebeak_-_Genius.mp4/file	https://image.tmdb.org/t/p/w500/firebreakMoviePoster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
The Secret Woman	An investigative reporter uncovers the mysterious double life of a missing socialite, unraveling deep secrets that powerful figures will kill to conceal.	Genius	Drama, Mystery, Thriller	5700	2024	https://www.mediafire.com/file/z8tiauuvfp0pl5x/The_Secret_Woman_-_Genius.mp4/file	https://image.tmdb.org/t/p/w500/theSecretWomanPoster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com`;

const targetPath = path.join(process.cwd(), 'movies.csv');
const existingCsv = fs.readFileSync(targetPath, 'utf8');

const newLines = tsvData.trim().split('\n').map(line => {
  const parts = line.split('\t');
  return parts.map(p => `"${(p || '').trim().replace(/"/g, '""')}"`).join(',');
});

let appended = 0;
for (const line of newLines) {
  const titleMatch = line.match(/^"([^"]+)"/);
  const title = titleMatch ? titleMatch[1] : '';
  if (!existingCsv.includes(`"${title}"`)) {
    fs.appendFileSync(targetPath, '\n' + line);
    appended++;
  }
}

console.log(`Appended ${appended} new records from batch 3 to movies.csv.`);
