import fs from 'fs';
import path from 'path';

const tsvData = `Furious Attack	A hardened fighter is forced back into the underground combat circuit when criminal elements threaten the lives of his family.	Sankara da Premier	Action, Thriller	5400	2024	https://www.mediafire.com/file/a5gbis8ujp0qtei/Furios_Attack.mp4/file	https://image.tmdb.org/t/p/w500/furiousAttackPosterPath.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
One Last Shot	An aging hitman decides to take on one final, high-risk assignment to secure freedom for his estranged daughter.	Sankara da Premier	Action, Crime, Thriller	5760	2024	https://www.mediafire.com/file/6w5370ax61sub9z/One_last_shot_sankara.mp4/file	https://image.tmdb.org/t/p/w500/oneLastShotPosterPath.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Knights of the Zodiac	When a goddess of war reincarnates in the body of a young girl, street orphan Seiya discovers that he is destined to protect her and save the world.	Sankara da Premier	Action, Adventure, Fantasy	6720	2023	https://www.mediafire.com/file/512927brfvzqt0l/Knight_Of_Zodiac_Sankra.mp4/file	https://image.tmdb.org/t/p/w500/qW4crfED8mpNDadSmMdi7Spzh9X.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Kung Fu Jungle - Part A	A martial arts instructor from a police academy gets imprisoned after killing a man by accident. When a vicious killer starts targeting martial arts masters, he offers to help the police in exchange for his freedom.	Sankara da Premier	Action, Crime, Thriller	3180	2014	https://www.mediafire.com/file/kds6dvvixn3t4iy/Kung_Fu_Jungle_A_Hd.Mp4.mp4/file	https://image.tmdb.org/t/p/w500/7WqfR5q2Bq02a9uP67z56w7g0cZ.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Kung Fu Jungle - Part B	A martial arts instructor from a police academy gets imprisoned after killing a man by accident. When a vicious killer starts targeting martial arts masters, he offers to help the police in exchange for his freedom.	Sankara da Premier	Action, Crime, Thriller	3180	2014	https://www.mediafire.com/file/9mie4kwccjle3aq/Kung_Fu_Jungle_B_Hd.Mp4.mp4/file	https://image.tmdb.org/t/p/w500/7WqfR5q2Bq02a9uP67z56w7g0cZ.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Kung Fu Jungle - Part D	A martial arts instructor from a police academy gets imprisoned after killing a man by accident. When a vicious killer starts targeting martial arts masters, he offers to help the police in exchange for his freedom.	Sankara da Premier	Action, Crime, Thriller	3180	2014	https://www.mediafire.com/file/501yy66m4pezfyd/Kung_Fu_Jungle_D_Hd.Mp4.mp4/file	https://image.tmdb.org/t/p/w500/7WqfR5q2Bq02a9uP67z56w7g0cZ.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
A Quiet Place: Day One	A young woman named Sam finds herself trapped in New York City during the terrifying early moments of an invasion by alien creatures with ultrasonic hearing.	Sankara da Premier	Drama, Horror, Sci-Fi	5940	2024	https://www.mediafire.com/file/4gy9v9fo2uw34vn/AQUITEPLACEDAYONE.mp4/file	https://image.tmdb.org/t/p/w500/yrpPYK2qm9Le6GBkG3b5hv7FzC5.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Step Up: All In - Part A	All-stars from the previous Step Up installments come together in glittering Las Vegas, battling for a victory that could define their dreams and their careers.	Sankara da Premier	Drama, Music, Romance	3360	2014	https://www.mediafire.com/file/qvtq7ltyq8nzoez/Step_Up_All_In_A_Hd.mp4/file	https://image.tmdb.org/t/p/w500/aM3tZ8oGjGk5r4p9fT0r8h2d3iB.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Step Up: All In - Part B	All-stars from the previous Step Up installments come together in glittering Las Vegas, battling for a victory that could define their dreams and their careers.	Sankara da Premier	Drama, Music, Romance	3360	2014	https://www.mediafire.com/file/qkt6jdjbb6ay72s/Step_Up_All_In_B_Hd.mp4/file	https://image.tmdb.org/t/p/w500/aM3tZ8oGjGk5r4p9fT0r8h2d3iB.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
How High	Two marijuana-smokers cultivate a magical strain that helps them ace their college entrance exams, landing them scholarships at Harvard University.	Sankara da Premier	Comedy, Fantasy	5580	2001	https://www.mediafire.com/file/ep7h2xmkvm81o01/How_High_1_Hd.mp4/file	https://image.tmdb.org/t/p/w500/6yqDq2kU9yH1u8XvT5a0B3Z0w2a.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Mutiny	Framed for the murder of his billionaire boss, a private security agent uncovers a vast international conspiracy while fighting for survival on the high seas.	Sankara da Premier	Action, Thriller	6300	2026	https://www.mediafire.com/file/rdlhay8x126ycpk/Mutiny_2026.mp4/file	https://image.tmdb.org/t/p/w500/mutiny2026PosterPath500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Evil Dead Rise: Burn	A twisted tale of flesh-possessing demons thrusting estranged family members into a primal battle for survival in an abandoned high-rise building.	Sankara da Premier	Horror	5760	2026	https://www.mediafire.com/file/rasdl65qreqsfkh/Evil_dead_burn_2026.mp4/file	https://image.tmdb.org/t/p/w500/5ik4r19m2w5u78a8f1n2c3d4e5f.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Skin Trade - Part A	After his family is murdered by a Serbian gangster with international interests, NYC detective Nick Cassidy heads to Southeast Asia to team up with a Thai detective and seek revenge.	Sankara da Premier	Action, Crime, Thriller	2880	2014	https://www.mediafire.com/file/lenq3eog8oau5c0/Skin_Trade_A_Hd.mp4/file	https://image.tmdb.org/t/p/w500/q2Z8F7v0w9Y6l7z3u4r5a6b7c8d.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Skin Trade - Part B	After his family is murdered by a Serbian gangster with international interests, NYC detective Nick Cassidy heads to Southeast Asia to team up with a Thai detective and seek revenge.	Sankara da Premier	Action, Crime, Thriller	2880	2014	https://www.mediafire.com/file/hdriy5gvr213pmh/Skin_Trad_B_Hd.mp4/file	https://image.tmdb.org/t/p/w500/q2Z8F7v0w9Y6l7z3u4r5a6b7c8d.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Addicted	A successful businesswoman who seemingly has it all risks losing her family and career as her insatiable sexual appetite spirals completely out of control.	Sankara da Premier	Drama, Thriller	6360	2014	https://www.mediafire.com/file/ycwp6himv0opq36/Addicted_Hd.mp4/file	https://image.tmdb.org/t/p/w500/v4B6u9q7Y9x2X1c3v5n8m0p2a4b.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Death's Game Ep 1	Facing imminent death by suicide, a desperate man is punished by Death to endure death over and over again through 12 different reincarnations.	Sankara da Premier	Fantasy, Thriller, Drama	3300	2023	https://www.mediafire.com/file/mga817e9igc9x7b/Death_Game_Ep1.mp4/file	https://image.tmdb.org/t/p/w500/m8B0Yj6x5o4R4a5m6c7d8e9f0a1.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Death's Game Ep 2	Facing imminent death by suicide, a desperate man is punished by Death to endure death over and over again through 12 different reincarnations.	Sankara da Premier	Fantasy, Thriller, Drama	3300	2023	https://www.mediafire.com/file/d4n75qsdp84snkp/Death_game_Ep2.mp4/file	https://image.tmdb.org/t/p/w500/m8B0Yj6x5o4R4a5m6c7d8e9f0a1.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Death's Game Ep 3	Facing imminent death by suicide, a desperate man is punished by Death to endure death over and over again through 12 different reincarnations.	Sankara da Premier	Fantasy, Thriller, Drama	3300	2023	https://www.mediafire.com/file/lu4d8tfidpdmf7f/Death_game_Ep3.mp4/file	https://image.tmdb.org/t/p/w500/m8B0Yj6x5o4R4a5m6c7d8e9f0a1.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Death's Game Ep 4	Facing imminent death by suicide, a desperate man is punished by Death to endure death over and over again through 12 different reincarnations.	Sankara da Premier	Fantasy, Thriller, Drama	3300	2023	https://www.mediafire.com/file/g58v0p04apyjzti/Death_game_Ep4.mp4/file	https://image.tmdb.org/t/p/w500/m8B0Yj6x5o4R4a5m6c7d8e9f0a1.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Death's Game Ep 5	Facing imminent death by suicide, a desperate man is punished by Death to endure death over and over again through 12 different reincarnations.	Sankara da Premier	Fantasy, Thriller, Drama	3300	2023	https://www.mediafire.com/file/h06ckf0df4egp9h/Death_game_Ep5.mp4/file	https://image.tmdb.org/t/p/w500/m8B0Yj6x5o4R4a5m6c7d8e9f0a1.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Death's Game Ep 6	Facing imminent death by suicide, a desperate man is punished by Death to endure death over and over again through 12 different reincarnations.	Sankara da Premier	Fantasy, Thriller, Drama	3300	2023	https://www.mediafire.com/file/qodocyf81229sxc/Death_game_Ep6.mp4/file	https://image.tmdb.org/t/p/w500/m8B0Yj6x5o4R4a5m6c7d8e9f0a1.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Death's Game Ep 7	Facing imminent death by suicide, a desperate man is punished by Death to endure death over and over again through 12 different reincarnations.	Sankara da Premier	Fantasy, Thriller, Drama	3300	2023	https://www.mediafire.com/file/l8jkonoy10nzuxt/Death_game_Ep7.mp4/file	https://image.tmdb.org/t/p/w500/m8B0Yj6x5o4R4a5m6c7d8e9f0a1.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Death's Game Ep 8 Final	Facing imminent death by suicide, a desperate man is punished by Death to endure death over and over again through 12 different reincarnations.	Sankara da Premier	Fantasy, Thriller, Drama	3300	2023	https://www.mediafire.com/file/306io9sw8xrwt8y/Death_game_Ep8.mp4/file	https://image.tmdb.org/t/p/w500/m8B0Yj6x5o4R4a5m6c7d8e9f0a1.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Rise of the Legend	An orphaned prodigy rises through the ranks of the Black Tiger gang in 19th-century Guangzhou, seeking vengeance for his father's murder and becoming the folk hero Wong Fei-hung.	Sankara da Premier	Action, Biography, Drama	7860	2014	https://www.mediafire.com/file/rhr4buiyd8wn7co/Rise_Of_The_Legend_Hd.mp4/file	https://image.tmdb.org/t/p/w500/b3Z7a8s9d0f1g2h3j4k5l6m7n8p.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
The Girlfriend Ep 1	A thrilling romantic drama exploring dark obsessions, hidden pasts, and lethal deceit when an idyllic relationship uncovers unsettling secrets.	Sankara da Premier	Drama, Mystery, Thriller	2700	2026	https://www.mediafire.com/file/qinwj78gkrt2t98/The_girlfriend.mp4/file	https://image.tmdb.org/t/p/w500/theGirlfriendSeriesPoster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
The Girlfriend Ep 2	A thrilling romantic drama exploring dark obsessions, hidden pasts, and lethal deceit when an idyllic relationship uncovers unsettling secrets.	Sankara da Premier	Drama, Mystery, Thriller	2700	2026	https://www.mediafire.com/file/jiskxoqadyc8tkp/The_girlfriend_S01_Ep2_Hd.mp4/file	https://image.tmdb.org/t/p/w500/theGirlfriendSeriesPoster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
The Girlfriend Ep 3	A thrilling romantic drama exploring dark obsessions, hidden pasts, and lethal deceit when an idyllic relationship uncovers unsettling secrets.	Sankara da Premier	Drama, Mystery, Thriller	2700	2026	https://www.mediafire.com/file/g96iuvji296o7et/The_girlfriend_S01_Ep3_Hd.mp4/file	https://image.tmdb.org/t/p/w500/theGirlfriendSeriesPoster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
The Girlfriend Ep 4	A thrilling romantic drama exploring dark obsessions, hidden pasts, and lethal deceit when an idyllic relationship uncovers unsettling secrets.	Sankara da Premier	Drama, Mystery, Thriller	2700	2026	https://www.mediafire.com/file/ckthququ81t6x7j/The_girlfriend_S01_Ep4_Hd.mp4/file	https://image.tmdb.org/t/p/w500/theGirlfriendSeriesPoster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
The Girlfriend Ep 5	A thrilling romantic drama exploring dark obsessions, hidden pasts, and lethal deceit when an idyllic relationship uncovers unsettling secrets.	Sankara da Premier	Drama, Mystery, Thriller	2700	2026	https://www.mediafire.com/file/vb6gqzkvnel04k1/The_girlfriend_S01_Ep5_Hd.mp4/file	https://image.tmdb.org/t/p/w500/theGirlfriendSeriesPoster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
The Girlfriend Ep 6 Final	A thrilling romantic drama exploring dark obsessions, hidden pasts, and lethal deceit when an idyllic relationship uncovers unsettling secrets.	Sankara da Premier	Drama, Mystery, Thriller	2700	2026	https://www.mediafire.com/file/xute14jfmbj1clc/The_Girlfriend_Ep6.mp4/file	https://image.tmdb.org/t/p/w500/theGirlfriendSeriesPoster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Daybreakers	In the year 2019, a plague has transformed almost every human into a vampire. Faced with a dwindling blood supply, an undercover group of researchers works with humans to find an antidote.	Sankara da Premier	Action, Horror, Sci-Fi	5880	2009	https://www.mediafire.com/file/tr1v9n48pde2g9v/Watch_Day_breaker_%25282020%2529_1.mp4/file	https://image.tmdb.org/t/p/w500/b8t4x5u8p9a0s1d2f3g4h5j6k7l.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Bad Sister	A manipulative and mentally unstable woman infiltrates a wealthy family by posing as an innocent nanny, harboring sinister motives.	Sankara da Premier	Drama, Mystery, Thriller	5220	2015	https://www.mediafire.com/file/cbc1i4sylr8i61q/BAD_SISTER.mp4/file	https://image.tmdb.org/t/p/w500/badSisterMoviePoster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Fighter (2026)	An elite IAF aviator forms an elite combat team to safeguard Indian airspace from hostile international incursions in daring dogfights.	Sankara da Premier	Action, Thriller, War	9960	2024	https://www.mediafire.com/file/wufvq0n6r29vqu3/Watch_Figther_2026.mp4/file	https://image.tmdb.org/t/p/w500/fighter2024PosterPath500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
The Furious	An operative battles across foreign underground networks to rescue a kidnapped witness targeted by powerful corrupt cartels.	Sankara da Premier	Action, Crime, Thriller	6180	2026	https://www.mediafire.com/file/pixq3wkodejuqh8/The_furious_%25282026%2529.mp4/file	https://image.tmdb.org/t/p/w500/theFurious2026PosterPath500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
The Myth	Archaeologist Jack keeps having dreams of a past life as General Meng Yi, an officer tasked with protecting a princess during the Qin Dynasty.	Sankara da Premier	Action, Adventure, Fantasy	7320	2005	https://www.mediafire.com/file/lfopf5a6fexsqk0/The_Myth_Hd.mp4/file	https://image.tmdb.org/t/p/w500/theMythJackieChanPoster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com
Fuze	A defused World War II bomb unearthed at a London construction site sparks a high-stakes standoff as an unhinged mercenary group plots a robbery amidst the mass evacuation.	Sankara da Premier	Action, Crime, Thriller	6000	2025	https://www.mediafire.com/file/kucmfqzayt8asow/Fuze_Sankra_.mp4/file	https://image.tmdb.org/t/p/w500/fuzeMoviePoster500.jpg			0	0	FALSE	TRUE	admin@fiestaflix.com`;

const targetPath = path.join(process.cwd(), 'movies.csv');
const existingCsv = fs.readFileSync(targetPath, 'utf8');

const newLines = tsvData.trim().split('\n').map(line => {
  const parts = line.split('\t');
  return parts.map(p => `"${(p || '').trim().replace(/"/g, '""')}"`).join(',');
});

let appended = 0;
for (const line of newLines) {
  const titleMatch = line.match(/^"([^"]+)"/);
  const title = titleMatch ? titleMatch[1] : '';
  if (!existingCsv.includes(`"${title}"`)) {
    fs.appendFileSync(targetPath, '\n' + line);
    appended++;
  }
}

console.log(`Appended ${appended} new records from batch 1 to movies.csv.`);
